### ISSUE TITLE
关于do_snapshot问题请教

### ISSUE THREAD

**Issue by xuefengchang** [baidu/braft#163]
有两个问题请教下：
1. snapshot和apply的串行化是靠bthread::execution_queue_execute的提交任务的顺序来保证的吗？
2. 如果状态机本身数据很大(比如4G)，每次打snapshot耗时很长，这样是会导致打快照期间日志一直不能提交吗？

**Comment by hnwyllmm** [comment]
snapshot和apply都是同一个任务队列
如果snapshot比较大，可以异步执行，我们的snapshot都是几百G的
可以参考issue 73   https://github.com/brpc/braft/issues/73

**Comment by dongdongwcpp** [comment]
> snapshot和apply都是同一个任务队列
> 如果snapshot比较大，可以异步执行，我们的snapshot都是几百G的
> 可以参考issue 73 #73
> 还有readme里面的
> https://github.com/brpc/braft/blob/master/docs/cn/server.md 实现Snapshot 这一节

rocksdb 在create snapshot很快，但是createCheckpoint 很慢，但是似乎没有办法在snapshot上创建checkpoint，因为要刷memtable等等数据？
