### ISSUE TITLE
on_configuration_committed 回调次数的问题

### ISSUE THREAD

**Issue by walterzhaoJR** [baidu/braft#180]
目前有遇到过一个现象：
1.在将一个节点添加到一个raft group中（AddPeer操作）去的时候，发现on_configuration_committed被回调两次，具体情况如下：
2.假设raft group为A B，将C 加入这个raft group中的时候，第一次C节点回调on_configuration_committed时获取到的peer list是A,B，第二次C回调on_configuration_committed的时候，获取到的peer list为ABC。前提是我对butil::Status NodeImpl::list_peers(std::vector<PeerId>* peers)做了一点改造，去掉了是leader的限制，这个是否有影响呢。还有就是两次回调on_configuration_committed是否合理呢
![image](https://user-images.githubusercontent.com/22393698/69537536-4e965f00-0fbb-11ea-9754-c05b371ebf64.png)

**Comment by Edward-xk** [comment]
> 目前有遇到过一个现象：
> 1.在将一个节点添加到一个raft group中（AddPeer操作）去的时候，发现on_configuration_committed被回调两次，具体情况如下：
> 2.假设raft group为A B，将C 加入这个raft group中的时候，第一次C节点回调on_configuration_committed时获取到的peer list是A,B，第二次C回调on_configuration_committed的时候，获取到的peer list为ABC。前提是我对butil::Status NodeImpl::list_peers(std::vector* peers)做了一点改造，去掉了是leader的限制，这个是否有影响呢。还有就是两次回调on_configuration_committed是否合理呢
> ![image](https://user-images.githubusercontent.com/22393698/69537536-4e965f00-0fbb-11ea-9754-c05b371ebf64.png)

1. 去掉了是leader的限制 没有太大影响，我们加上这个是为了在更新配置前做一把check(需要在leader上做)
2. 两次回调on_configuration_committed 应该是因为{A} -> {AB}这个过程的log也在C上on_apply了一次，这个是符合预期的

**Comment by walterzhaoJR** [comment]
@Edward-xk THX

**Comment by walterzhaoJR** [comment]
@Edward-xk 还有点疑问，麻烦能解答下。
1.我去掉了butil::Status NodeImpl::list_peers(std::vector* peers)中对leader的限制，只为了在follower节点上方便获取到成员列表，不知道是否有更好的方式？
2.有没有什么办法可以明确知道一次成员变更的完成？

**Comment by Edward-xk** [comment]
> @Edward-xk 还有点疑问，麻烦能解答下。
> 1.我去掉了butil::Status NodeImpl::list_peers(std::vector* peers)中对leader的限制，只为了在follower节点上方便获取到成员列表，不知道是否有更好的方式？
> 2.有没有什么办法可以明确知道一次成员变更的完成？

1.也可以在业务层维护一个Configuration，在on_configuration_committed时更新它。但在成员变更的过程中，看到的节点列表不一定是准的，可能有一点延迟
2.调用成员变更接口时传入一个Closure的子类，该子类在Run()函数里检查status().ok()即可。如果是true即表示成功完成了

**Comment by PFZheng** [comment]
follower上的configuration可能是过期的，只有leader是准确的
