### ISSUE TITLE
Single-Server Change Problem.

### ISSUE THREAD

**Issue by htner** [baidu/braft#182]
https://github.com/baidu/braft/blob/master/docs/cn/raft_protocol.md中提到：

> **Single-Server Change**
> 其实上面的流程可以简化，每次只增删一个节点，这样就不会出现两个多数集合，不会造成决议冲突的情况。按照如下规则进行处理：
> 
> 1. Leader收到AddPeer/RemovePeer的时候就进行处理，而不是等到committed，这样马上就可以使用新的peer set进行复制AddPeer/RemovePeer请求。
> 2. Leader启动的时候就发送NO_OP请求，将上一个AddPeer/RemovePeer变为committed。
> 3. Leader在删除自身节点的时候，会在RemovePeer被Committed之后，进行关闭。
> 按照上面的规则，可以实现安全的动态节点增删
> 

其中第二点，描述不够准确。

>  Leader启动的时候就发送NO_OP请求，将上一个AddPeer/RemovePeer变为committed

[按照作者的讨论:](https://groups.google.com/forum/#!topic/RAFT-dev/t4xj6dJTP6E)
 In a typical Raft implementation, a leader appends a no-op entry to the log when it is elected. This change would mean rejecting or delaying membership change requests until the no-op entry is committed.
Once a leader has committed an entry in its current term, it knows it has the latest committed configuration, and no existing uncommitted configurations from prior terms can be committed anymore (the servers that store the current leader's entry won't vote for the servers that have the uncommitted configuration). So then it is safe for the leader to create a new configuration (that differs by at most one server) and begin replicating it.

其中第二点，
2. Leader启动的时候就发送NO_OP请求，将上一个AddPeer/RemovePeer变为committed。直等到NO_OP请求committed之后, 可以安全地创建一个新的configuration并开始复制它。

**Comment by htner** [comment]
细细看原文的写法流程也没有原则上的问题。 只是文章描述不够详细，容易引起歧义。

**Comment by tanzhongyibidu** [comment]
You can add a pr for it，
It will help others，thanks

发件人: Ivan <notifications@github.com>
答复: baidu/braft <reply@reply.github.com>
日期: 2019年12月18日 星期三 下午4:31
收件人: baidu/braft <braft@noreply.github.com>
抄送: Subscribed <subscribed@noreply.github.com>
主题: Re: [baidu/braft] Single-Server Change Problem. (#182)


细细看原文的写法流程也没有原则上的问题。 只是文章描述不够详细，容易引起歧义。
