### ISSUE TITLE
Where are the documents and examples for using braft as stateSynchronizer(example: zookeeper)?

### ISSUE THREAD

**Issue by wuchangping** [baidu/braft#185]
Where are the documents and examples for using braft as stateSynchronizer(example)?
We want to use braft as stateSynchronizer to replace zookeeper, but braft is not easy to use, based on current examples and documents,

 are there other documents and examples?

**Comment by jamesge** [comment]
For replacement of zookeeper, consider [etcd](https://github.com/etcd-io/etcd) first.

**Comment by wuchangping** [comment]
> For replacement of zookeeper, consider [etcd](https://github.com/etcd-io/etcd) first.

Thanks.
