### ISSUE TITLE
新leader在commit旧的log entry后会响应client吗

### ISSUE THREAD

**Issue by yc1037642433** [baidu/braft#186]
leader节点在一个log entry还未commit时就发生了leader切换，那么新的leader节点在commit该log entry后，会发送响应给client吗？新leader如何知道client的ip，因为log entry里面没有保护request的done。

**Comment by PFZheng** [comment]
done是内存里的数据，client超时重试时发送到新的leader

**Comment by Edward-xk** [comment]
> leader节点在一个log entry还未commit时就发生了leader切换，那么新的leader节点在commit该log entry后，会发送响应给client吗？新leader如何知道client的ip，因为log entry里面没有保护request的done。

不会。这种情况需要依赖client的重试以及请求的幂等性。
