### ISSUE TITLE
RocksDB example

### ISSUE THREAD

**Issue by kishorenc** [baidu/braft#189]
Is there a reason why the RocksDB example was removed? 

https://github.com/baidu/braft/commit/39bcf4d21e6f3930d90b16917f37e606f90ac444

Any gotchas that I should be aware of if I plan to use that?

P.S: Thanks for making this amazing library available.

**Comment by PFZheng** [comment]
It's ok to use this example.

I guess the reason why this example is removed, it' that, braft don't want to introduce RocksDB as a dependency. @chenzhangyi
