### ISSUE TITLE
自带的 counter QPS 只有 800 左右

### ISSUE THREAD

**Issue by ideawu** [baidu/braft#193]
我在测试 braft, 但是发现 qps 极低, 请问这种情况是否正常?

使用默认的 counter 例子, 只启动单个节点. server 和 client 启动方法如下:

```
./server --conf="127.0.0.1:8100:0"
./client --conf="127.0.0.1:8100:0"
```

client 输出如下:

```
I0314 09:52:53.899330 20205 example/counter/client.cpp:134] Sending Request to Counter (127.0.0.1:8100:0) at qps=740 latency=1221
I0314 09:52:54.899707 20205 example/counter/client.cpp:134] Sending Request to Counter (127.0.0.1:8100:0) at qps=799 latency=1149
I0314 09:52:55.900274 20205 example/counter/client.cpp:134] Sending Request to Counter (127.0.0.1:8100:0) at qps=820 latency=1143
I0314 09:52:56.900839 20205 example/counter/client.cpp:134] Sending Request to Counter (127.0.0.1:8100:0) at qps=815 latency=1137
```

作为对比, 同样环境的 redis 数据如下:

```
./redis-benchmark -c 1 -n 1000 -t set
====== SET ======
  1000 requests completed in 0.24 seconds
  1 parallel clients
  3 bytes payload
  keep alive: 1

100.00% <= 0 milliseconds
4115.23 requests per second
```

差距非常大. 经过打点, 发现 node.apply() 到 on_apply() 的延时有 1~2ms. 请问, 这种情况是否符合设计预期呢? 或是我需要做什么参数调整?

**Comment by ideawu** [comment]
补充: client 并发 50 个的数据如下:

```
# ./client --conf="127.0.0.1:8100:0" --thread_num 50
I0314 10:12:29.910130 21391 example/counter/client.cpp:134] Sending Request to Counter (127.0.0.1:8100:0) at qps=1950 latency=23296
I0314 10:12:30.910450 21391 example/counter/client.cpp:134] Sending Request to Counter (127.0.0.1:8100:0) at qps=2005 latency=24892
```

作为对比:

```
# ./redis-benchmark -c 50 -n 100000 -t set
====== SET ======
  100000 requests completed in 2.68 seconds
  50 parallel clients
  3 bytes payload
  keep alive: 1

45.41% <= 1 milliseconds
99.73% <= 2 milliseconds
99.97% <= 3 milliseconds
99.98% <= 4 milliseconds
99.99% <= 5 milliseconds
99.99% <= 6 milliseconds
100.00% <= 6 milliseconds
37341.30 requests per second
```

**Comment by PFZheng** [comment]
这里主要的区别应该是磁盘的性能。
raft log 是需要落盘的，且默认情况下开启的是最强的持久化选项，raft_sync = true，这个会导致每次落盘都执行一次 fsync。
可以把 log 的存储位置 tmpfs 再测试一下，tmpfs 的数据是在内存里。或者使用 braft 自带的 memory log，log 路径前的 "local:" 改为 “memory:”。

**Comment by ideawu** [comment]
Hello, 由于我所测试的业务场景是持久化存储, 所以, 把所有 raft 自身的数据存在于内存而不持久是不可接受的. 基于你的建议, 我重新做了测试, redis 做了配置变更:

```
appendonly yes
appendfsync always
```

所以, raft_sync 默认为 true 才是符合业务场景的选项, 所以这里不修改. 数据如下:

### 首先是串行化请求(1连接)

```
# ./client --conf="127.0.0.1:8100:0" --thread_num=1
I0315 03:25:12.587582 19627 example/counter/client.cpp:134] Sending Request to Counter (127.0.0.1:8100:0) at qps=1160 latency=765
I0315 03:25:13.587831 19627 example/counter/client.cpp:134] Sending Request to Counter (127.0.0.1:8100:0) at qps=1089 latency=837
I0315 03:25:14.588123 19627 example/counter/client.cpp:134] Sending Request to Counter (127.0.0.1:8100:0) at qps=1242 latency=749

# ./src/redis-benchmark -c 1 -n 1000 -t incr
====== INCR ======
  1000 requests completed in 0.85 seconds
  1 parallel clients
  3 bytes payload
  keep alive: 1

98.70% <= 1 milliseconds
100.00% <= 1 milliseconds
1170.96 requests per second
```

可见,  确实如你所说, 是 fsync 影响性能. 这项测试 braft 和 redis 结果相近, 都是 1000 qps 左右, 是 ok 的. 这里主要受客户端和服务端 rtt 的影响.

### 接着是 50 个并发

```
# ./client --conf="127.0.0.1:8100:0" --thread_num=50
I0315 03:30:29.422391 19646 example/counter/client.cpp:134] Sending Request to Counter (127.0.0.1:8100:0) at qps=3740 latency=12796
I0315 03:30:30.422601 19646 example/counter/client.cpp:134] Sending Request to Counter (127.0.0.1:8100:0) at qps=3084 latency=16198
I0315 03:30:31.422830 19646 example/counter/client.cpp:134] Sending Request to Counter (127.0.0.1:8100:0) at qps=2987 latency=16501

# ./src/redis-benchmark -c 50 -n 10000 -t incr
====== INCR ======
  10000 requests completed in 0.44 seconds
  50 parallel clients
  3 bytes payload
  keep alive: 1

0.01% <= 1 milliseconds
32.54% <= 2 milliseconds
98.56% <= 3 milliseconds
99.30% <= 4 milliseconds
99.51% <= 9 milliseconds
99.57% <= 10 milliseconds
99.84% <= 11 milliseconds
100.00% <= 11 milliseconds
22935.78 requests per second
```

结果是 3000 vs 23000, 8 倍的差距.

由于 counter example 是(状态机, 非 raft 自己)纯内存操作, 这已经是所有基于 braft 开发的最简化的业务的极限.

大家讨论一下: 下一步能优化的空间在哪呢?

**Comment by ideawu** [comment]
### Methods

* braft counter example
    * default options: raft_sync=true
* redis
    * appendonly yes
    * appendfsync always

braft(average):

```
./counter-client --conf="127.0.0.1:8100:0" --thread_num=1
```

redis:

```
./redis-benchmark -c 1 -n 1000 -t incr
```

### Result

connections | braft | redis
------------|-------|-----
1   | 1283 | 1025
10  | 2900 | 4948
50  | 2741 | 23969
100 | 2675 | 40567

**Comment by killme2008** [comment]
multi raft group 是可以考虑的方案，拆成多分组。单个 raft group 的性能是很难再去提高的，在保证数据不丢和强一致的情况下，基本受限于你的磁盘性能。

**Comment by PFZheng** [comment]
按照你的测试方法，用一台百度云上的单核虚机做了一下测试，磁盘类型是50G的HDD：

thread count = 50 的时候：
[root@instance-fekj86zq counter]# sh ./run_client.sh --thread_num=50 --server_num=1
I0315 13:28:55.988862 27075 /mnt/vdc/braft/braft/example/counter/client.cpp:134] Sending Request to Counter (192.168.64.4:8100:0,) at qps=0 latency=0
I0315 13:28:56.989099 27075 /mnt/vdc/braft/braft/example/counter/client.cpp:134] Sending Request to Counter (192.168.64.4:8100:0,) at qps=1900 latency=26082
I0315 13:28:57.989240 27075 /mnt/vdc/braft/braft/example/counter/client.cpp:134] Sending Request to Counter (192.168.64.4:8100:0,) at qps=2101 latency=23431

thread count = 100 的时候：
[root@instance-fekj86zq counter]# sh ./run_client.sh --thread_num=100 --server_num=1
I0315 13:30:02.901866 27331 /mnt/vdc/braft/braft/example/counter/client.cpp:134] Sending Request to Counter (192.168.64.4:8100:0,) at qps=0 latency=0
I0315 13:30:03.902098 27331 /mnt/vdc/braft/braft/example/counter/client.cpp:134] Sending Request to Counter (192.168.64.4:8100:0,) at qps=4202 latency=23447
I0315 13:30:04.902239 27331 /mnt/vdc/braft/braft/example/counter/client.cpp:134] Sending Request to Counter (192.168.64.4:8100:0,) at qps=3999 latency=25094

thread count = 500 的时候：
[root@instance-fekj86zq counter]# sh ./run_client.sh --thread_num=500 --server_num=1
I0315 13:30:32.052693 27492 /mnt/vdc/braft/braft/example/counter/client.cpp:134] Sending Request to Counter (192.168.64.4:8100:0,) at qps=0 latency=0
I0315 13:30:33.052981 27492 /mnt/vdc/braft/braft/example/counter/client.cpp:134] Sending Request to Counter (192.168.64.4:8100:0,) at qps=15876 latency=30803
I0315 13:30:34.053465 27492 /mnt/vdc/braft/braft/example/counter/client.cpp:134] Sending Request to Counter (192.168.64.4:8100:0,) at qps=16131 latency=31046

thread count = 1000 的时候：
[root@instance-fekj86zq counter]# sh ./run_client.sh --thread_num=1000 --server_num=1
I0315 13:31:01.586292 27696 /mnt/vdc/braft/braft/example/counter/client.cpp:134] Sending Request to Counter (192.168.64.4:8100:0,) at qps=0 latency=0
I0315 13:31:02.586527 27696 /mnt/vdc/braft/braft/example/counter/client.cpp:134] Sending Request to Counter (192.168.64.4:8100:0,) at qps=17167 latency=56573
I0315 13:31:03.586664 27696 /mnt/vdc/braft/braft/example/counter/client.cpp:134] Sending Request to Counter (192.168.64.4:8100:0,) at qps=19087 latency=52496

raft 使用的 brpc 自带的网页（ip:port 即可打开，统计数据在 bvar 标签下）可以帮助分析其中的性能。
看落盘的延时，这里差不多在 11ms的样子：
![image](https://user-images.githubusercontent.com/3984083/76696038-ef6f6e00-66c1-11ea-885f-9e6c8f22ee89.png)
raft log storage部分有batch策略，最大batch size 是256，看下面平均batch size的图，已经比较接近了。
![image](https://user-images.githubusercontent.com/3984083/76696083-51c86e80-66c2-11ea-8e30-64e5e3ed203f.png)
这样的话，摊平到每个请求的落盘时间为：
11ms/256=43us
那么，即使其它部分的开销大小为0，极限qps约为：
1000000/43=2.3w

**Comment by PFZheng** [comment]
50并发度下的结果主要还是延时决定的。
提高代码里的batch size能够进一步减小摊平的时间，不过意义不大，实际场景下的log size会比这个example大很多。更大的batch size只有对跑分有意义。
在实际的使用中，如果是性能敏感的同时又必须打开raft_sync，可以将log放在SSD等高速介质上

**Comment by PFZheng** [comment]
在HDD上multi-raft也一定不会更好，默认实现的多路日志会将IO变成并发随机IO，性能会更差。做日志合并，日志部分最后的效果和单raft差不多，on_apply部分因为可以并发的原因会好一些。

**Comment by PFZheng** [comment]
再补充一个redis的测试结果：

[root@instance-fekj86zq counter]# redis-benchmark -c 50 -n 10000 -t incr
====== INCR ======
  10000 requests completed in 2.42 seconds
  50 parallel clients
  3 bytes payload
  keep alive: 1

[root@instance-fekj86zq counter]# redis-benchmark -c 100 -n 10000 -t incr
====== INCR ======
  10000 requests completed in 2.34 seconds
  100 parallel clients
  3 bytes payload
  keep alive: 1

[root@instance-fekj86zq counter]# redis-benchmark -c 1000 -n 10000 -t incr
====== INCR ======
  10000 requests completed in 0.26 seconds
  1000 parallel clients
  3 bytes payload
  keep alive: 1

connections | braft | redis
-- | -- | --
50 | 2000 | 4132
100 | 16000 | 4273
1000 |19000| 38461

redis 100的时候有点儿反常，测了几次都是差不多的结果

**Comment by killme2008** [comment]
> 在HDD上multi-raft也不一定会更好，默认实现的多路日志会将IO变成并发随机IO，性能会更差。做日志合并，日志部分最后的效果和单raft差不多，on_apply部分因为可以并发的原因会好一些。

如果机器有多块盘的话，还是会有比较好的效果。

**Comment by PFZheng** [comment]
> > 在HDD上multi-raft也不一定会更好，默认实现的多路日志会将IO变成并发随机IO，性能会更差。做日志合并，日志部分最后的效果和单raft差不多，on_apply部分因为可以并发的原因会好一些。
> 
> 如果机器有多块盘的话，还是会有比较好的效果。

嗯，是的。慢盘上主要瓶颈还是磁盘的速度

**Comment by ideawu** [comment]
@PFZheng 你的 redis 测试有一点需要改进的地方:

```
redis-benchmark -c 1000 -n 10000 -t incr
```

这里 `-n` 需要加大, 因为这是指所有连接发起的请求总数. 当你用 1000 个连接时, 最好每个连接发 1000 个请求, 那就是 `-n` 取一百万.

**Comment by chenzhangyi** [comment]
架构上有提升就两点:
1. client端做batch, 对于counter来说实际上是算作弊，对于server来说n个请求实际上就对应一个log
2. server端对于写buffer和sync做pipeline。

对于大部分应用来说，1只在刷分时候有用，2算一个通用的改进.

**Comment by ideawu** [comment]
我找了一台真实的机器做测试, 结果看起来比较符合预期, 我开始做测试是在一台 mbp 上的 docker unbuntu 里, 所以测试结果离预期差距非常大.

### Result - Ubuntu docker on macOS

connections | braft | redis
------------|-------|-----
1   | 1283 | 1025
10  | 2900 | 4948
50  | 2741 | 23969
100 | 2675 | 40567

### Result - Real machine

```
Intel(R) Xeon(R) Silver 4110 CPU @ 2.10GHz
256 GB mem 2666 MHz
SSD unknown
Linux 4.9.70
```

connections | braft | redis
------------|-------|-----
1    | 2147   | 3787
10   | 15544  | 20366
100  | 83163  | 95693
1000 | 161080 | 92592
