### ISSUE TITLE
stepdown时，清理ClosureQueue时，有可能有些已经达成一致，是否会导致丢数据？

### ISSUE THREAD

**Issue by zhongleihe** [baidu/braft#197]
void ClosureQueue::clear() {
    std::deque<Closure*> saved_queue;
    {
        BAIDU_SCOPED_LOCK(_mutex);
        saved_queue.swap(_queue);
        _first_index = 0;
    }
    bool run_bthread = false;
    for (std::deque<Closure*>::iterator 
            it = saved_queue.begin(); it != saved_queue.end(); ++it) {
        if (*it) {
            (*it)->status().set_error(EPERM, "leader stepped down");
            run_closure_in_bthread_nosig(*it, _usercode_in_pthread);
            run_bthread = true;
        }
    }
    if (run_bthread) {
        bthread_flush();
    }
}
这个函数中清理的closure，有可能已经达成一致，如果不区分一下直接清理掉，并且给done赋值(EPERM, "leader stepped down")，会有以下问题：
（1）清理掉的已经达成一致的log，当自己成为follower时，不会再重建到ClosureQueue中，这部分log没有机会调用用户自己实现的on_apply函数，但一般on_apply都是应用的状态机中的，这时候会导致数据丢失。（没有看到follower回补这部分数据的逻辑）；
（2）在transfer_leader时，会导致更过的"leader stepped down"。
这个函数是否可以有区别的清理，只是把那些没有达成一致的请求的closure清理掉，即等待applied_index追上commited_index之后再清理ClosureQueue。当然这样可能导致transfer_leader的时间会长一些，但在某些业务场景下这样更合适。

**Comment by chenzhangyi** [comment]
已经commit的log不会被清理，事实上任何log都不会被主动清理，都要等到和后续leader对应位置的log term对不上的时候才会执行清理.
在分布式场景下，false negative是没法完全规避的问题，为了特殊几个场景去等待是否日志被提交没有意义，反而更及时的提醒client leader已经切换是更好的方法，这样如果log没有commit，能更早的提交给新的leader
具体到transfer leadership， 这里可以考虑等到log都commit之后再去，这个需要评估下对切换延迟的影响.

**Comment by zhongleihe** [comment]
1、我表述的是有点问题，这里不应该叫做清理log，应该叫清理没有达成一致的log对应的内存中的closure。这里如果清理了，以后有可能就没有机会再调用用户实现的on_apply了，而on_apply一般会把log应用到状态机中。
2、我们是做分布式数据库的，任何悬而未决的log，我们会自杀进程，这个成本有点高。

**Comment by chenzhangyi** [comment]
on_apply本身和closure没有关系, log commit之后总会调用的，这里无论怎么实现都不会导致状态机的不一致，自杀进程的原因是什么？

**Comment by zhongleihe** [comment]
transfer_leader完成后转变成leader的清理逻辑：step_down-->clear_pending_tasks-->_closure_queue->clear()，在这个里面把closure清理掉了（里面有可能有些已经达成一致），比方说index为999的log已经达成一致，但closure被清理掉了。
假设是A transfer_leader 到B，假设这个时候的log_manager的last_index是1000，那么transfer_leader完后B的last_index也是1000，A作为B的follower的next_index也是1000。B只可能从1000以后去复制日志，那么A的上的index为999的log是如何被应用的呢？有可能有些代码细节我没有注意到？
目前自杀是因为我们的事务模型不能重试，不过对于transfer_leader的场景到是可以到新leader上去查询下去。但无论如何都会有悬而未决自杀的情况。

**Comment by PFZheng** [comment]
> 1、我表述的是有点问题，这里不应该叫做清理log，应该叫清理没有达成一致的log对应的内存中的closure。这里如果清理了，以后有可能就没有机会再调用用户实现的on_apply了，而on_apply一般会把log应用到状态机中。
> 2、我们是做分布式数据库的，任何悬而未决的log，我们会自杀进程，这个成本有点高。

closure 和日志 on_apply 是两个事情，这个就类似网络超时，closure 的结果可以类比 client 看到的超时，server端是否完成操作和client看到的这个超时结果没有关联。状态机回调 on_apply 的时候这条日志是确定committed的

**Comment by zhongleihe** [comment]
> on_apply本身和closure没有关系, log commit之后总会调用的，这里无论怎么实现都不会导致状态机的不一致，自杀进程的原因是什么？

这块的逻辑看到了，谢谢解答；我们自杀的原因是有些情况下，不能重试，所以只要raft不能确定是否成功，我们都会自杀。

**Comment by luobuda** [comment]
@zhongleihe 你好，可以交流一下这个问题吗
