### ISSUE TITLE
系统盘满后出现node state ERROR，清理系统盘仍无法恢复正常

### ISSUE THREAD

**Issue by xuxlz** [baidu/braft#200]
您好，我在单机上面试着使用braft的时候，把系统盘写满了，进程都还在。删了一些无关文件后（braft相关的没有删），查看日志发现braft node状态一直是ERROR无法自动恢复，无法选主，需要全部重启才能正常。        
想请教一下，这种有没有什么好的解决方法？还是只能全部重启才行？谢谢！          
            
braft版本：release 1.0.2                      
brpc版本：release 0.9.6                  
日志：W0305 13:42:52.082983 16426 /root/braft/src/braft/node.cpp:1816] node Metaserver:192.168.152.33:8112:0 is not in active state current_term 15 state ERROR

**Comment by chenzhangyi** [comment]
磁盘错误没法自动恢复，需要重启, raft再进行一系列的检查之后才能恢复状态。

**Comment by xuxlz** [comment]
> 磁盘错误没法自动恢复，需要重启, raft再进行一系列的检查之后才能恢复状态。

哦这样呀，好的，谢谢

**Comment by xuxlz** [comment]
@chenzhangyi 您好，抱歉打扰，我想再请教一下磁盘写满的问题。                 
我测试了3个node的情况（node A/B/C），对应的log分别写入3个盘（盘A/B/C），3个盘上除了braft log还有些其他程序的日志。盘A写满后，清理其他日志文件重启却无法使服务正常，显示该node的term和last log大于其他两个peer，只能先删除该盘的log，通过其他两个node的log才能使服务恢复。同时我也试了把3个盘按A/B/C顺序依次写满，发现只删除最先写满的那个盘的log就能恢复。                
想问下这是什么原因呢？在3个盘都满的情况下，是否可能有数据丢失？有没有什么更好的方法能恢复服务？                 
盼回复，谢谢！
