### ISSUE TITLE
关于leader_lease续租时机

### ISSUE THREAD

**Issue by zhongleihe** [baidu/braft#202]
近期看到你们上了期待已久的leader_lease与follower_lease功能，迫不及待的读了一下，有个问题想请教下：
leader_lease通过LeaderLease::renew来续租更新_last_active_timestamp，但正常状态下调用renew的只有get_leader_lease_status，is_leader_lease_valid又调用get_leader_lease_status。内部没有调用这两个接口。这样做是要leader续租是由使用者自己控制吗？另外在get_leader_lease_status这个get接口中去做set的事情是不是不太合适？

**Comment by PFZheng** [comment]
这里是为了避免减少软件实现上的误差的影响（定时器、调度等），需要在check lease状态的时候主动去调用get_leader_lease_status，续租的操作本身是随着心跳更新的。
在get里面有set是为了使检查的操作lazy化，避免每次都去做繁重的检查，在lease确信的有效期内，快速判定lease有效。

**Comment by PFZheng** [comment]
最理想的一个 lease 实现是通过回调机制来通知客户, 当 leader 上 lease 开始/过期的时候, 用户收到 on_lease_start/on_lease_stop 回调. 但是, lease 失效的时刻很难去发现。通常的做法是用定时器，但是有一些问题：

- 定时器的精度问题，那定时器的唤醒周期要远小于时钟漂移的最大值才行，这会带来很大的开销。
- 大部分定时器实现其实就是一个普通的线程池 job，这里从定时器触发到执行也存在不确定的时间差。

综上, 主动检查的机制是更合适的选择。在此基础上，进一步减少检查的开销。

**Comment by zhongleihe** [comment]
> 最理想的一个 lease 实现是通过回调机制来通知客户, 当 leader 上 lease 开始/过期的时候, 用户收到 on_lease_start/on_lease_stop 回调. 但是, lease 失效的时刻很难去发现。通常的做法是用定时器，但是有一些问题：
> 
> * 定时器的精度问题，那定时器的唤醒周期要远小于时钟漂移的最大值才行，这会带来很大的开销。
> * 大部分定时器实现其实就是一个普通的线程池 job，这里从定时器触发到执行也存在不确定的时间差。
> 
> 综上, 主动检查的机制是更合适的选择。在此基础上，进一步减少检查的开销。

在之前braft没有leader_lease和follower_lease时在某个时间段是可能存在两个leader的情况的。比方说：a、b、c三个节点，有下面的状态序列：（假设选举超时时间是10s）
1、a是leader，a b c之前网络状态良好；
2、ab |c  ab与c之间发生网络隔离，并且在网络隔离期间没有数据写入；
3、在时刻100s时，a|bc发生网络隔离；
4、在时刻101时，bc之间的网络恢复，但ac没有恢复，这时b争取到了c的投票，变成leader；
5、在110s时，a在经历一个选举超时时间后主动check b、c是否活着，由于网络不通，a step down为follower；
在上面的分析中，在101到110这段时间集群中有两个leader。
考虑下面一种使用场景：
用户基于lease_read要实现类似于spanner的外部一致性，client A和clientB是数据库的两个客户端，有下面的执行序列
1、clientA一直连的是a，假设在时刻102之前，value都是200；
2、在103s时clientB连上了变成leader的c，并且把value变成了300；
那么在103到110这段时间clientA读取的都是value200，而clientB读取的是value300，这是不符合外部一致性要求的。
咱们增加了leader_lease和follower_lease之后，这种情况可以避免，但是需要使用者每次读之前都调用下get_leader_lease_status？这个成本有点高啊。我想到可能通过下面方式来解决：
1、用户调用get_leader_lease_status时把自己还有多久lease过期告诉用户，由用户决定定时去check，比方说用户发现还有1s就过期了，那么用户认为这时候读时不安全的，就禁止读；
2、定时器不够准确的确是个问题，但是否可以做的保守一点，比方说10s的选举超时时间，如果5s的时候还没有收到大部分节点的心跳回复，就主动step_down。

**Comment by PFZheng** [comment]
> > 最理想的一个 lease 实现是通过回调机制来通知客户, 当 leader 上 lease 开始/过期的时候, 用户收到 on_lease_start/on_lease_stop 回调. 但是, lease 失效的时刻很难去发现。通常的做法是用定时器，但是有一些问题：
> > 
> > * 定时器的精度问题，那定时器的唤醒周期要远小于时钟漂移的最大值才行，这会带来很大的开销。
> > * 大部分定时器实现其实就是一个普通的线程池 job，这里从定时器触发到执行也存在不确定的时间差。
> > 
> > 综上, 主动检查的机制是更合适的选择。在此基础上，进一步减少检查的开销。
> 
> 在之前braft没有leader_lease和follower_lease时在某个时间段是可能存在两个leader的情况的。比方说：a、b、c三个节点，有下面的状态序列：（假设选举超时时间是10s）
> 1、a是leader，a b c之前网络状态良好；
> 2、ab |c ab与c之间发生网络隔离，并且在网络隔离期间没有数据写入；
> 3、在时刻100s时，a|bc发生网络隔离；
> 4、在时刻101时，bc之间的网络恢复，但ac没有恢复，这时b争取到了c的投票，变成leader；
> 5、在110s时，a在经历一个选举超时时间后主动check b、c是否活着，由于网络不通，a step down为follower；
> 在上面的分析中，在101到110这段时间集群中有两个leader。
> 考虑下面一种使用场景：
> 用户基于lease_read要实现类似于spanner的外部一致性，client A和clientB是数据库的两个客户端，有下面的执行序列
> 1、clientA一直连的是a，假设在时刻102之前，value都是200；
> 2、在103s时clientB连上了变成leader的c，并且把value变成了300；
> 那么在103到110这段时间clientA读取的都是value200，而clientB读取的是value300，这是不符合外部一致性要求的。
> 咱们增加了leader_lease和follower_lease之后，这种情况可以避免，但是需要使用者每次读之前都调用下get_leader_lease_status？这个成本有点高啊。我想到可能通过下面方式来解决：
> 1、用户调用get_leader_lease_status时把自己还有多久lease过期告诉用户，由用户决定定时去check，比方说用户发现还有1s就过期了，那么用户认为这时候读时不安全的，就禁止读；
> 2、定时器不够准确的确是个问题，但是否可以做的保守一点，比方说10s的选举超时时间，如果5s的时候还没有收到大部分节点的心跳回复，就主动step_down。

成本是相对的，不管是怎么实现，在读之前判断状态是必不可少的，因为大概率读的线程和执行写的不是一个线程。这里至少是一个原子变量的开销，contention足够短的情况下，锁的开销和原子变量是差不多的。在这里不把时间返回，一个考虑点braft是支持vote/transfer leader情况下的lease 安全的，直接返回时间无法保证这一点，因为在认为有效的期间内，leader可能被另外一个节点抢走。
你需要的这种lease实现可以通过用户侧周期 append log来实现。考虑到外围实现比较简便（集成到braft里也不会有太大差异），同时在限制vote/transfer leader的情况下比较安全，没有采用这个方案。
