### ISSUE TITLE
成员配置变更过程能否中断

### ISSUE THREAD

**Issue by wangxun155423** [baidu/braft#204]
braft配置变更过程中，有stage状态限制，不允许并发进行，但能否中断之前变更呢。
考虑这样的一个常见的场景：如一个Group中三原节点ABC，加入一个新节点D，目标配置是ABCD，D在接收快照数据的过程中宕机 永久无法工作了，那这种情形该怎么处理原leader A发起的本次变更呢，目前我想到的是节点进行重启好像可以中断本次变更，但会影响可用性，不重启的话呢？

**Comment by Edward-xk** [comment]
> braft配置变更过程中，有stage状态限制，不允许并发进行，但能否中断之前变更呢。
> 考虑这样的一个常见的场景：如一个Group中三原节点ABC，加入一个新节点D，目标配置是ABCD，D在接收快照数据的过程中宕机 永久无法工作了，那这种情形该怎么处理原leader A发起的本次变更呢，目前我想到的是节点进行重启好像可以中断本次变更，但会影响可用性，不重启的话呢？

如果在追数据阶段（你的case属于这种）新节点宕机，那么这次change_peers最后会返回ECATCHUP, 此时其实还没真的开始节点变更行为，这种情况如果业务层通过管理模块（需自行实现）发现新节点宕机，那么直接终止不再重试就行了；
如果已经完成追数据并进入正式节点变更流程，那么只要旧节点集的多数和新节点集的多数都可用，变更流程就会成功。类似你举的例子，ABC -> ABCD的过程，即使D在变更过程中宕机了，流程还是会成功。后续如监测到宕机且不可恢复，可以再调用一次change_peers下掉这个节点就行了

**Comment by wangxun155423** [comment]
> > braft配置变更过程中，有stage状态限制，不允许并发进行，但能否中断之前变更呢。
> > 考虑这样的一个常见的场景：如一个Group中三原节点ABC，加入一个新节点D，目标配置是ABCD，D在接收快照数据的过程中宕机 永久无法工作了，那这种情形该怎么处理原leader A发起的本次变更呢，目前我想到的是节点进行重启好像可以中断本次变更，但会影响可用性，不重启的话呢？
> 
> 如果在追数据阶段（你的case属于这种）新节点宕机，那么这次change_peers最后会返回ECATCHUP, 此时其实还没真的开始节点变更行为，这种情况如果业务层通过管理模块（需自行实现）发现新节点宕机，那么直接终止不再重试就行了；
> 如果已经完成追数据并进入正式节点变更流程，那么只要旧节点集的多数和新节点集的多数都可用，变更流程就会成功。类似你举的例子，ABC -> ABCD的过程，即使D在变更过程中宕机了，流程还是会成功。后续如监测到宕机且不可恢复，可以再调用一次change_peers下掉这个节点就行了

感谢回复，明白了，看到braft里面的catchup机制 会通过D节点的存活状态判断是否要继续重试
