### ISSUE TITLE
Node和Replicator问题请教

### ISSUE THREAD

**Issue by xuxlz** [baidu/braft#205]
想请教一下：
1.Node相关文档描述“PeerId结构是一个EndPoint表示对外服务的端口, 外加一个index(默认为0)”，这里的index是出于什么考虑设计的呀？
2.在测试的时候，发现entry多时，Replicator::_send_entries()到Replicator::_on_rpc_returned会很慢，这种可能是处于什么原因？

**Comment by xuxlz** [comment]
想请教一下：
1.Node相关文档描述“PeerId结构是一个EndPoint表示对外服务的端口, 外加一个index(默认为0)”，这里的index是出于什么考虑设计的呀？             
2.在测试的时候，发现entry多时，Replicator::_send_entries()到Replicator::_on_rpc_returned会很慢，这种可能是处于什么原因？

**Comment by Edward-xk** [comment]
> 想请教一下：
> 1.Node相关文档描述“PeerId结构是一个EndPoint表示对外服务的端口, 外加一个index(默认为0)”，这里的index是出于什么考虑设计的呀？
> 2.在测试的时候，发现entry多时，Replicator::_send_entries()到Replicator::_on_rpc_returned会很慢，这种可能是处于什么原因？

1.multi-raft的场景里，一个副本可能被删除再创建，且新、旧副本可能落到同一个server上，增加index可以避免一些异常情况下的ABA问题。
2.这个可能和磁盘性能有关系，因为这个rpc要等follower上日志落盘。raft_sync 这个 flag 可控制是否sync, 默认为 true, 可调为 false 观察一下差别

**Comment by xuxlz** [comment]
> > 想请教一下：
> > 1.Node相关文档描述“PeerId结构是一个EndPoint表示对外服务的端口, 外加一个index(默认为0)”，这里的index是出于什么考虑设计的呀？
> > 2.在测试的时候，发现entry多时，Replicator::_send_entries()到Replicator::_on_rpc_returned会很慢，这种可能是处于什么原因？
> 
> 1.multi-raft的场景里，一个副本可能被删除再创建，且新、旧副本可能落到同一个server上，增加index可以避免一些异常情况下的ABA问题。
> 2.这个可能和磁盘性能有关系，因为这个rpc要等follower上日志落盘。raft_sync 这个 flag 可控制是否sync, 默认为 true, 可调为 false 观察一下差别

谢谢！我去试试
