### ISSUE TITLE
升级和Replicator问题请教

### ISSUE THREAD

**Issue by xuxlz** [baidu/braft#213]
请问一下：          
1.做业务升级的时候，braft是否有推荐的升级流程或方法？           
2.构造Task向braft::Node提交后，是否可能出现超时失败（比如因网络问题）？如果会出现超时，这个超时时长是多少呢？braft会删去这个task，然后通过ClosureGuard回调吗？             
3.raft_sync这个flag设置为false后，我在测试时发现性能有很大提升，这个flag为何默认为true呢？是些场景下必须设置为true吗？                
谢谢！

**Comment by PFZheng** [comment]
1. 直接升级就行了，无需特殊处理；
2. raft内部无超时时间的概念，协议的要求和实际的实现都是内部无限重试。业务层可以自行实现超时和重试幂等处理逻辑。leader stepdown的时候closure会回调，其他情况下会一直等待直到成功才会回调；
3. raft_sync是每一次写日志后都会附加一个fsync操作。true是数据最安全的设置，如果改成false，掉电情况下数据会有丢失风险

**Comment by xuxlz** [comment]
> 1. 直接升级就行了，无需特殊处理；
> 2. raft内部无超时时间的概念，协议的要求和实际的实现都是内部无限重试。业务层可以自行实现超时和重试幂等处理逻辑。leader stepdown的时候closure会回调，其他情况下会一直等待直到成功才会回调；
> 3. raft_sync是每一次写日志后都会附加一个fsync操作。true是数据最安全的设置，如果改成false，掉电情况下数据会有丢失风险

谢谢！
