### ISSUE TITLE
last_msg_to_now不更新

### ISSUE THREAD

**Issue by niukuo** [baidu/braft#214]
28c50d5b77b43af5c5f31cf71aaec4df31ce4c01
是这个commit引入的。
导致 raft_stat 中 last_msg_to_now启动后不更新，调查中

**Comment by niukuo** [comment]
本地测试时cherry-pick了03bbb29f6b528c2d1c8531a658378337ad297f4d，不然编译不过。

**Comment by PFZheng** [comment]
嗯，是有问题，这个变量在现在的代码里没更新了

**Comment by PFZheng** [comment]
看起来是之前某个patch就问题了，我排查下

**Comment by niukuo** [comment]
已提交pull request #215

**Comment by niukuo** [comment]
fixed in #216
