### ISSUE TITLE
unsafe_truncate_suffix core

### ISSUE THREAD

**Issue by zhangqiang4002** [baidu/braft#218]
![image](https://user-images.githubusercontent.com/16186116/83987155-e7963180-a971-11ea-9e06-c9694ced2a29.png)

version: braft-1.1.0

**Comment by chenzhangyi** [comment]
CHECK失败会输出具体原因的，贴一下看看是什么

**Comment by zhangqiang4002** [comment]
> CHECK失败会输出具体原因的，贴一下看看是什么

对应core时间点的 FATAL.20200608-014218.97451: No such file or directory

**Comment by zhangqiang4002** [comment]
> > CHECK失败会输出具体原因的，贴一下看看是什么
> 
> 对应core时间点的 FATAL.20200608-014218.97451: No such file or directory

![image](https://user-images.githubusercontent.com/16186116/83988868-24b0f280-a977-11ea-841a-040c780b47ea.png)

**Comment by PFZheng** [comment]
CHECK_EQ(0, bthread::execution_queue_execute(_disk_queue, tsc));
是这一行吗？

**Comment by PFZheng** [comment]
是不是有同名的复制组？截图日志里是已经apply的日志被truncate，这个一般在脑裂的时候会发生

**Comment by zhangqiang4002** [comment]
> CHECK_EQ(0, bthread::execution_queue_execute(_disk_queue, tsc));
> 是这一行吗？
> 
> 如果是的话，感觉是前面就失败了，_disk_queue是无效的

不是， 是这里FATAL日志退出了
![image](https://user-images.githubusercontent.com/16186116/84025794-c14ab300-a9be-11ea-8cdb-e3bdc6e90766.png)

**Comment by zhangqiang4002** [comment]
> 是不是有同名的复制组？截图日志里是已经apply的日志被truncate，这个一般在脑裂的时候会发生

很有可能，服务中有频繁的复制组创建、删除操作，偶现raft log不一致的情况。这里强制退出是否必须的呢？对服务影响表较大

**Comment by zhangqiang4002** [comment]
暂时把FATAL改为ERROR规避强制退出，似乎最后也能自动恢复到正确的状态
![image](https://user-images.githubusercontent.com/16186116/84097983-9dc44e80-aa38-11ea-9573-24407db2049d.png)
![image](https://user-images.githubusercontent.com/16186116/84097991-a157d580-aa38-11ea-82d5-17c8482bedf9.png)

**Comment by PFZheng** [comment]
> > CHECK_EQ(0, bthread::execution_queue_execute(_disk_queue, tsc));
> > 是这一行吗？
> > 如果是的话，感觉是前面就失败了，_disk_queue是无效的
> 
> 不是， 是这里FATAL日志退出了
> ![image](https://user-images.githubusercontent.com/16186116/84025794-c14ab300-a9be-11ea-8cdb-e3bdc6e90766.png)

这个地方就是出现了数据回退，想要强行truncate掉已经被状态机应用的日志。FATAL改成ERROR只是掩耳盗铃，数据可能已经丢失了。这种情况下，一致性没有任何保证。
系统中的Raft不同复制组需要保证不重名，副本变更通过add_peer/remove_peer/change_peer来操作。

**Comment by zhangqiang4002** [comment]
> > > CHECK_EQ(0, bthread::execution_queue_execute(_disk_queue, tsc));
> > > 是这一行吗？
> > > 如果是的话，感觉是前面就失败了，_disk_queue是无效的
> > 
> > 
> > 不是， 是这里FATAL日志退出了
> > ![image](https://user-images.githubusercontent.com/16186116/84025794-c14ab300-a9be-11ea-8cdb-e3bdc6e90766.png)
> 
> 这个地方就是出现了数据回退，想要强行truncate掉已经被状态机应用的日志。FATAL改成ERROR只是掩耳盗铃，数据可能已经丢失了。这种情况下，一致性没有任何保证。
> 系统中的Raft不同复制组需要保证不重名，副本变更通过add_peer/remove_peer/change_peer来操作。

谢谢，我们查到是调用braft::cli::reset_peer导致的， 想办法修改下
![image](https://user-images.githubusercontent.com/16186116/84099308-e3cee180-aa3b-11ea-8dfb-83ec931ffed2.png)

**Comment by PFZheng** [comment]
> > > > CHECK_EQ(0, bthread::execution_queue_execute(_disk_queue, tsc));
> > > > 是这一行吗？
> > > > 如果是的话，感觉是前面就失败了，_disk_queue是无效的
> > > 
> > > 
> > > 不是， 是这里FATAL日志退出了
> > > ![image](https://user-images.githubusercontent.com/16186116/84025794-c14ab300-a9be-11ea-8cdb-e3bdc6e90766.png)
> > 
> > 
> > 这个地方就是出现了数据回退，想要强行truncate掉已经被状态机应用的日志。FATAL改成ERROR只是掩耳盗铃，数据可能已经丢失了。这种情况下，一致性没有任何保证。
> > 系统中的Raft不同复制组需要保证不重名，副本变更通过add_peer/remove_peer/change_peer来操作。
> 
> 谢谢，我们查到是调用braft::cli::reset_peer导致的， 想办法修改下
> ![image](https://user-images.githubusercontent.com/16186116/84099308-e3cee180-aa3b-11ea-8dfb-83ec931ffed2.png)

reset_peer是一个极度危险的运维命令，如果不是进入quorum dead，数据已经无法通过Raft自身恢复，不要调用该接口，正常的变更走add_peer/remove/change_peer。在reset_peer时候，需要确保被删除的副本被销毁掉了。

**Comment by zhangqiang4002** [comment]
如果复制组leader节点不存在且存活节点已经小于半数，这时候add_peer/remove/change_peer都不能执行，该如何操作呢？

**Comment by Edward-xk** [comment]
> 如果复制组leader节点不存在且存活节点已经小于半数，这时候add_peer/remove/change_peer都不能执行，该如何操作呢？

调reset_peer接口，但是要保证被删除的副本被GC掉。有些情况“dead”是一种假死状态，重启可能恢复正常，如果reset_peer把这些节点从复制组中去掉，但没GC后续又被重启恢复，就有可能出现脑裂。

**Comment by zhangqiang4002** [comment]
非常感谢，问题已经解决。
