### ISSUE TITLE
raft group merge功能

### ISSUE THREAD

**Issue by GOGOYAO** [baidu/braft#220]
现在braft支持raft group的split，那么merge有支持么？

**Comment by PFZheng** [comment]
> 现在braft支持raft group的split，那么merge有支持么？

没有支持

**Comment by GOGOYAO** [comment]
> > 现在braft支持raft group的split，那么merge有支持么？
> 
> 没有支持

未来有考虑么？
或者就目前版本的braft，有啥方法做region的合并？

**Comment by PFZheng** [comment]
> > > 现在braft支持raft group的split，那么merge有支持么？
> > 
> > 
> > 没有支持
> 
> 未来有考虑么？
> 或者就目前版本的braft，有啥方法做region的合并？

这个光靠 braft 不是很好搞，raft 协议自己不理解数据，需要的外围的工作比较多。我能想到的方法有这样几个：

方法1: 让需要合并的 region 的副本调度到同样的节点上，写日志让其中一个复制组停止接受新的写，另外一个复制组写一条日志将数据继承过来（如果是基于rocksdb之类的共享存储，比较好操作），同时触发一次snapshot，形成新的 base。在这之后，可以放开配置变更了。
方法2：利用类似 split 的机制，同样调度到同样的机器上，让需要合并的两个复制组都停写，bootstrap启动一个新复制组，继承两者的数据。
方法3：一个复制组从另外一个复制组直接拖取数据通过raft log写到本复制组。这里需要外围处理好这期间的读写处理。

**Comment by GOGOYAO** [comment]
> > > > 现在braft支持raft group的split，那么merge有支持么？
> > > 
> > > 
> > > 没有支持
> > 
> > 
> > 未来有考虑么？
> > 或者就目前版本的braft，有啥方法做region的合并？
> 
> 这个光靠 braft 不是很好搞，raft 协议自己不理解数据，需要的外围的工作比较多。我能想到的方法有这样几个：
> 
> 方法1: 让需要合并的 region 的副本调度到同样的节点上，写日志让其中一个复制组停止接受新的写，另外一个复制组写一条日志将数据继承过来（如果是基于rocksdb之类的共享存储，比较好操作），同时触发一次snapshot，形成新的 base。在这之后，可以放开配置变更了。
> 方法2：利用类似 split 的机制，同样调度到同样的机器上，让需要合并的两个复制组都停写，bootstrap启动一个新复制组，继承两者的数据。
> 方法3：一个复制组从另外一个复制组直接拖取数据通过raft log写到本复制组。这里需要外围处理好这期间的读写处理。

了解。感谢
