### ISSUE TITLE
server_id和peer_id的区别

### ISSUE THREAD

**Issue by GOGOYAO** [baidu/braft#222]
学习源码的时候发现，ReplicatorOptions中有两个成员变量
```
PeerId server_id;
PeerId peer_id;
```
使用的时候，很多地方又用的peer_id来初始化server_id（比如ReplicatorGroup::init函数），那么这俩是有啥区别呢？还是说就是一个东西？

**Comment by PFZheng** [comment]
其实是一个东西。Replicator 里的 server_id 是自己，peer_id 是对端

**Comment by GOGOYAO** [comment]
> peer_id

除了Replicator里面，其他地方也是这个含义（Replicator 里的 server_id 是自己，peer_id 是对端）吧？
