### ISSUE TITLE
add_peer_returned回调函数的疑问

### ISSUE THREAD

**Issue by GOGOYAO** [baidu/braft#225]
`add_peer_returned`的最后一个参数是`const butil::Status& st`，根据brpc中`callback.h`的注释
```
// Note that NewCallback() is a bit touchy regarding argument types.  Generally,
// the values you provide for the parameter bindings must exactly match the
// types accepted by the callback function.  For example:
//   void Foo(string s);
//   NewCallback(&Foo, "foo");          // WON'T WORK:  const char* != string
//   NewCallback(&Foo, string("foo"));  // WORKS
// Also note that the arguments cannot be references:
//   void Foo(const string& s);
//   string my_str;
//   NewCallback(&Foo, my_str);  // WON'T WORK:  Can't use referecnes.
// However, correctly-typed pointers will work just fine.
```
回调函数中不应该有引用，那么这里的实现应该是有问题的吧？

另外还有个问题，add_peer_returned的定义，是有7个参数，但是在使用的时候，仅传入了6个（少了最后一个const butil::Status& st），求问这里是不是也有点不对劲？

**Comment by chenzhangyi** [comment]
braft的[NewCallback](https://github.com/baidu/braft/blob/master/src/braft/closure_helper.h) 实现不是直接用的brpc的实现.
这里的status是braft::Closure的内部成员.
这个是c++03的遗留问题了, c++11时代不需要用这个

**Comment by GOGOYAO** [comment]
> braft的[NewCallback](https://github.com/baidu/braft/blob/master/src/braft/closure_helper.h) 实现不是直接用的brpc的实现.
> 这里的status是braft::Closure的内部成员.
> 这个是c++03的遗留问题了, c++11时代不需要用这个

c++11时代不需要用这个是指？

**Comment by chenzhangyi** [comment]
> > braft的[NewCallback](https://github.com/baidu/braft/blob/master/src/braft/closure_helper.h) 实现不是直接用的brpc的实现.
> > 这里的status是braft::Closure的内部成员.
> > 这个是c++03的遗留问题了, c++11时代不需要用这个
> 
> c++11时代不需要用这个是指？

c++11用lambda，代码会更直观一点

**Comment by GOGOYAO** [comment]
> > > braft的[NewCallback](https://github.com/baidu/braft/blob/master/src/braft/closure_helper.h) 实现不是直接用的brpc的实现.
> > > 这里的status是braft::Closure的内部成员.
> > > 这个是c++03的遗留问题了, c++11时代不需要用这个
> > 
> > 
> > c++11时代不需要用这个是指？
> 
> c++11用lambda，代码会更直观一点

get it
