### ISSUE TITLE
请教：Braft 编译通过，但是链接失败？？

### ISSUE THREAD

**Issue by triump2020** [baidu/braft#229]
1.环境：
ubuntu版本： Ubuntu 20.04 LTS
gcc/g++: 9.3.0
Make: 4.2.1
2.  复现步骤：
      BRPC 已经编译通过，下面编译BRAFT：
     1. 执行  cmake -DBRPC_INCLUDE_PATH=/home/luofei/BRPC/output/include -DBRPC_LIB=/home/luofei/BRPC/output/lib ..
        输出如下信息:
      
       The C compiler identification is GNU 9.3.0
-- The CXX compiler identification is GNU 9.3.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Failed
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE
-- Found Protobuf: /usr/lib/x86_64-linux-gnu/libprotobuf.so;-lpthread (found version "3.6.1")
-- Found OpenSSL: /usr/lib/x86_64-linux-gnu/libcrypto.so (found version "1.1.1f")
-- Configuring done
WARNING: Target "braft-static" requests linking to directory "/home/luofei/BRPC/output/lib".  Targets may link only to libraries.  CMake is dropping the item.
WARNING: Target "braft-shared" requests linking to directory "/home/luofei/BRPC/output/lib".  Targets may link only to libraries.  CMake is dropping the item.
WARNING: Target "braft_cli" requests linking to directory "/home/luofei/BRPC/output/lib".  Targets may link only to libraries.  CMake is dropping the item.
-- Generating done
-- Build files have been written to: /home/luofei/BRAFT/bld

    2>. 执行 make . 输出如下链接错误信息(在cmake 时候，已经指定了libbrpc的路径，为什么在链接过程中brpc库中的函数未找 
         到???):
      
/usr/bin/ld: CMakeFiles/braft_cli.dir/braft_cli.cpp.o: in function `main':
/home/luofei/BRAFT/tools/braft_cli.cpp:218: undefined reference to `butil::string_printf(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >*, char const*, ...)'
/usr/bin/ld: ../output/lib/libbraft.a(cli.cpp.o): in function `braft::cli::get_leader(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, braft::Configuration const&, braft::PeerId*) [clone .constprop.0]':
/home/luofei/BRAFT/src/braft/cli.cpp:49: undefined reference to `brpc::Controller::Failed() const'
/usr/bin/ld: /home/luofei/BRAFT/src/braft/cli.cpp:55: undefined reference to `butil::Status::error_str[abi:cxx11]() const'
/usr/bin/ld: /home/luofei/BRAFT/src/braft/cli.cpp:58: undefined reference to `brpc::Controller::ErrorText[abi:cxx11]() const'
/usr/bin/ld: /home/luofei/BRAFT/src/braft/cli.cpp:57: undefined reference to `butil::endpoint2str(butil::EndPoint const&)'
/usr/bin/ld: /home/luofei/BRAFT/src/braft/cli.cpp:45: undefined reference to `brpc::Controller::~Controller()'
/usr/bin/ld: /home/luofei/BRAFT/src/braft/cli.cpp:37: undefined reference to `brpc::Channel::~Channel()'
/usr/bin/ld: /home/luofei/BRAFT/src/braft/cli.cpp:37: undefined reference to `brpc::Channel::Channel(brpc::ProfilerLinker)'
/usr/bin/ld: /home/luofei/BRAFT/src/braft/cli.cpp:38: undefined reference to `brpc::Channel::Init(butil::EndPoint, brpc::ChannelOptions const*)'
/usr/bin/ld: /home/luofei/BRAFT/src/braft/cli.cpp:45: undefined reference to `brpc::Controller::Controller()'
/usr/bin/ld: ../output/lib/libbraft.a(cli.cpp.o): in function `braft::PeerId::to_string[abi:cxx11]() const':
/home/luofei/BRAFT/src/braft/configuration.h:75: undefined reference to `butil::endpoint2str(butil::EndPoint const&)'
/usr/bin/ld: ../output/lib/libbraft.a(cli.cpp.o): in function `braft::PeerId::parse(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)':
/home/luofei/BRAFT/src/braft/configuration.h:66: undefined reference to `butil::str2ip(char const*, in_addr*)'
/usr/bin/ld: ../output/lib/libbraft.a(cli.cpp.o): in function `braft::cli::get_leader(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, braft::Configuration const&, braft::PeerId*) [clone .constprop.0]':
/home/luofei/BRAFT/src/braft/cli.cpp:53: undefined reference to `brpc::Controller::ErrorText[abi:cxx11]() const'
/usr/bin/ld: /home/luofei/BRAFT/src/braft/cli.cpp:52: undefined reference to `butil::endpoint2str(butil::EndPoint const&)'
/usr/bin/ld: ../output/lib/libbraft.a(cli.cpp.o): in function `braft::PeerId::to_string[abi:cxx11]() const':
/home/luofei/BRAFT/src/braft/configuration.h:75: undefined reference to `butil::endpoint2str(butil::EndPoint const&)'
/usr/bin/ld: ../output/lib/libbraft.a(cli.cpp.o): in function `braft::cli::get_leader(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, braft::Configuration const&, braft::PeerId*) [clone .constprop.0]':
/usr/include/c++/9/ext/new_allocator.h:89: undefined reference to `brpc::Channel::~Channel()'
/usr/bin/ld: ../output/lib/libbraft.a(cli.cpp.o): in function `butil::Status::Status(butil::Status const&)':
/home/luofei/BRPC/output/include/butil/status.h:119: undefined reference to `butil::Status::copy_state(butil::Status::State const*)'
/usr/bin/ld: /home/luofei/BRPC/output/include/butil/status.h:119: undefined reference to `butil::Status::copy_state(butil::Status::State const*)'
/usr/bin/ld: ../output/lib/libbraft.a(cli.cpp.o): in function `braft::cli::add_peer(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, braft::Configuration const&, braft::PeerId const&, braft::cli::CliOptions const&)':
/home/luofei/BRAFT/src/braft/cli.cpp:75: undefined reference to `brpc::Channel::Channel(brpc::ProfilerLinker)'
/usr/bin/ld: /home/luofei/BRAFT/src/braft/cli.cpp:76: undefined reference to `brpc::Channel::Init(butil::EndPoint, brpc::ChannelOptions const*)'
/usr/bin/ld: ../output/lib/libbraft.a(cli.cpp.o): in function `braft::PeerId::to_string[abi:cxx11]() const':
/home/luofei/BRAFT/src/braft/configuration.h:75: undefined reference to `butil::endpoint2str(butil::EndPoint const&)'
/usr/bin/ld: /home/luofei/BRAFT/src/braft/configuration.h:75: undefined reference to `butil::endpoint2str(butil::EndPoint const&)'
/usr/bin/ld: ../output/lib/libbraft.a(cli.cpp.o): in function `braft::cli::add_peer(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, braft::Configuration const&, braft::PeerId const&, braft::cli::CliOptions const&)':
/home/luofei/BRAFT/src/braft/cli.cpp:85: undefined reference to `brpc::Controller::Controller()'
/usr/bin/ld: /home/luofei/BRAFT/src/braft/cli.cpp:86: undefined reference to `brpc::Controller::set_timeout_ms(long)'
/usr/bin/ld: /home/luofei/BRAFT/src/braft/cli.cpp:87: undefined reference to `brpc::Controller::set_max_retry(int)'
/usr/bin/ld: /home/luofei/BRAFT/src/braft/cli.cpp:91: undefined reference to `brpc::Controller::Failed() const'
/usr/bin/ld: ../output/lib/libbraft.a(cli.cpp.o): in function `braft::PeerId::parse(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)':
/home/luofei/BRAFT/src/braft/configuration.h:66: undefined reference to `butil::str2ip(char const*, in_addr*)'
/usr/bin/ld: /home/luofei/BRAFT/src/braft/configuration.h:66: undefined reference to `butil::str2ip(char const*, in_addr*)'
/usr/bin/ld: ../output/lib/libbraft.a(cli.cpp.o): in function `braft::cli::add_peer(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, braft::Configuration const&, braft::PeerId const&, braft::cli::CliOptions const&)':
/home/luofei/BRAFT/src/braft/cli.cpp:102: undefined reference to `logging::GetMinLogLevel()'
/usr/bin/ld: /home/luofei/BRAFT/src/braft/cli.cpp:85: undefined reference to `brpc::Controller::~Controller()'
/usr/bin/ld: ../output/lib/libbraft.a(cli.cpp.o): in function `braft::PeerId::to_string[abi:cxx11]() const':
/home/luofei/BRAFT/src/braft/configuration.h:75: undefined reference to `butil::endpoint2str(butil::EndPoint const&)'
/usr/bin/ld: ../output/lib/libbraft.a(cli.cpp.o): in function `braft::cli::add_peer(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, braft::Configuration const&, braft::PeerId const&, braft::cli::CliOptions const&)':
/home/luofei/BRAFT/src/braft/cli.cpp:75: undefined reference to `brpc::Channel::~Channel()'
/usr/bin/ld: ../output/lib/libbraft.a(cli.cpp.o): in function `logging::CheckEQImpl[abi:cxx11](int, int, char const*)':
/home/luofei/BRPC/output/include/butil/logging.h:636: undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >* logging::MakeCheckOpString<int, int>(int const&, int const&, char const*)'
/usr/bin/ld: ../output/lib/libbraft.a(cli.cpp.o): in function `braft::PeerId::PeerId(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)':
/home/luofei/BRAFT/src/braft/configuration.h:46: undefined reference to `logging::LogMessage::LogMessage(char const*, int, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >*)'
/usr/bin/ld: /home/luofei/BRAFT/src/braft/configuration.h:46: undefined reference to `logging::LogMessage::~LogMessage()'

谢谢！

**Comment by yusenfei** [comment]
@triump2020 题主能分享下解决方案吗，有同样的问题
