### ISSUE TITLE
raft_storage_append_entries_latency > rpc_server_8301_braft_raft_service_append_entries_latency

### ISSUE THREAD

**Issue by GOGOYAO** [baidu/braft#230]
![image](https://user-images.githubusercontent.com/18675094/91539435-e579b880-e94b-11ea-8fcb-ffa8e82782de.png)

如图发现raft_storage_append_entries_latency > rpc_server_8301_braft_raft_service_append_entries_latency

从代码实现看：
1. rpc_server_8301_braft_raft_service_append_entries_latency是接收到append_entries请求之后，到处理完并返回rpc信息整个过程的耗时
2. raft_storage_append_entries_latency记录的只是写log这个过程的耗时。
那么前者的时间应该是包含了后者的时间，所以不会出现raft_storage_append_entries_latency > rpc_server_8301_braft_raft_service_append_entries_latency才对。请指导

**Comment by GOGOYAO** [comment]
@PFZheng 求帮忙看下

**Comment by chenzhangyi** [comment]
append_entries应该包含了不需要写log的心跳的时间.

**Comment by GOGOYAO** [comment]
> append_entries应该包含了不需要写log的心跳的时间.

没太懂。求解释下

**Comment by chenzhangyi** [comment]
发送心跳和同步数据都是走的append_entries这个rpc接口，其中心跳只是判断下term之类的，不会有和磁盘交互的逻辑。 这个你可以再看下qps来验证下

> > append_entries应该包含了不需要写log的心跳的时间.
> 
> 没太懂。求解释下
