### ISSUE TITLE
bootstrap似乎存在内存泄漏？

### ISSUE THREAD

**Issue by Yriuns** [baidu/braft#233]
- NodeImpl::bootstrap后是否还需要调用NodeImpl::init？
  - 如果需要，NodeImpl::init_log_storage被调用了两次，导致LogManager被new两次
  - 如果不需要，该节点就没有new过BallotBox

**Comment by LittleTigered** [comment]
借问 NodeImpl::bootstrap和NodeImpl::init区别是啥呢， 各自在什么情况下使用
