### ISSUE TITLE
请问在handle_stepdown_timeout为什么不直接去检查_leader_lease

### ISSUE THREAD

**Issue by myccccccc** [baidu/braft#249]
https://github.com/baidu/braft/blob/0c5a5942a1df55ee7edf2f848404ee8ca1a64df3/src/braft/node.cpp#L773
在handle_stepdown_timeout中调用check_dead_nodes
https://github.com/baidu/braft/blob/0c5a5942a1df55ee7edf2f848404ee8ca1a64df3/src/braft/node.cpp#L785
通过遍历peers，检查每个peer的last_rpc_send_timestamp来判定目前还有没有超过半数follower
这里可不可以直接去调用
https://github.com/baidu/braft/blob/0c5a5942a1df55ee7edf2f848404ee8ca1a64df3/src/braft/node.cpp#L3231
来判定呢？

**Comment by PFZheng** [comment]
is_leader_lease_valid 是给外部用的，这里比valid，invalid还多一些不确定的状态。外围可服务的leader状态和raft leader状态不是完全等价的
