### ISSUE TITLE
_virtual_first_log_id 似乎没有用了？

### ISSUE THREAD

**Issue by zexuan** [baidu/braft#255]
不要意思，有个问题不理解，咨询一下：

leader save snapshot 之后，保留了last_but_one_snapshot_id.index到_last_snapshot_id.index之间的日志，因为复制日志有可能用到。set_snapshot中只有这种情况_virtual_first_log_id被设置成last_but_one_snapshot_id，其他情况都是_last_snapshot_id。

因此我理解_virtual_first_log_id日志复制的一个优化。但在复制日志时并没有用到。

leader复制数据给follower的时候，会在_prepare_entry中调用log_manager的get_entry函数。而get_entry函数中会判断index是否在[first_log_index, last_log_index]之间，不会用到_virtual_first_log_id。

其他地方也没有找到有必要使用 _virtual_first_log_id 的地方。

不知道是不是这个属性已经没有用了，还是我的理解有偏差？期待答复～ @PFZheng

**Comment by Edward-xk** [comment]
_virtual_first_log_id 在 LogManager::get_term 里会用到，实质是保留了倒数第二次 snapshot_id 所对应的 term, 这个是为了解决我们之前遇到的一个 corner case, 防止极端情况下连续触发 install_snapshot （这个时候尝试走复制日志的方式有一定概率能缓解问题）
