### ISSUE TITLE
支持init node的时候传递applyid

### ISSUE THREAD

**Issue by lintanghui** [baidu/braft#258]
* 描述：raft执行快照的时候，会保存当前已经apply的index到 snapshot meta。初始化raft node的时候，会加载raft meta读取last apply index，然后从last apply index开始继续执行状态机。对于大吞吐的场景，两次快照间隔可能有大量的数据，重启服务 init raft node的时候会造成大量数据重放导致启动过慢。
例如：
1. 第一次执行快照的last apply index为1000
2. 继续写入1w条数据并且已经提交到状态机
3. 此时节点重启，由于上一次快照的apply index是1000 因此raft会重新从1000开始回放日志。

* 解决方法： 对于kv服务，每次apply状态机的时候可以顺带更新last apply index。服务重启的时候从rocksdb 读取 last apply index，并在init raft node的时候传入。此时例子中的第三部只需要从 11000这个last apply index 进行重放即可，而不是从上一次的snapshot inedx进行重放导致大量io以及影响启动速度

**Comment by PFZheng** [comment]
apply 是可以跳过去的，如果节点本身有可信的 apply index。io 这个问题要复杂一些，这儿涉及到初始化时候的一些元信息的重建，此外还有连续性检查等工作

**Comment by Edward-xk** [comment]
这个 issue 百度厂内提过，但没有高优做：一方面这个需求并不是普适性的（只针对 base 和 snapshot 在一起的场景可用），另一方面这件事在业务层可以花较小的代价就能实现，有以下两个建议：
1.既然是 base 和 snapshot 在一起了（或者说状态已经是持久化的），那么 compaction 可以有很多种方式做成非常轻量级的，在这个前提下，可以适当缩小 raft 执行快照的周期，减小每次重启需要 replay 的日志数
2.业务层可持久化维护 applied_index, 重启时在 on_apply 接口里对于小于 applied_index 的日志不做处理直接返回

**Comment by lintanghui** [comment]
> 1.既然是 base 和 snapshot 在一起了（或者说状态已经是持久化的），那么 compaction 可以有很多种方式做成非常轻量级的，在这个前提下，可以适当缩小 raft 执行快照的周期，减小每次重启需要 replay 的日志数

缩小raft快照的周期可以减少重启replay的日志数，但是存在一个风险，当有节点故障恢复并从主节点install snapshot的时候，如果快照周期过小，可能当故障节点拷贝完snapshot的时候，主节点又再次做了一次snapshot。此时上一次snapshot的log index已经被删除，这个时候又需要重新发起 install snapshot。对于这个周期是否有best practice 推荐值设置。

> 2.业务层可持久化维护 applied_index, 重启时在 on_apply 接口里对于小于 applied_index 的日志不做处理直接返回

业务层面已经持久化保存了applied_index，并且在on_apply的时候直接跳过小于applied_index的日志。目前存在的问题是启动的时候如果快照间隔内写入量大，仍然会有大量的io影响启动速度。

**Comment by Edward-xk** [comment]
> 目前存在的问题是启动的时候如果快照间隔内写入量大，仍然会有大量的io影响启动速度。

这个场景可以具体描述下吗？

**Comment by lintanghui** [comment]
> > 目前存在的问题是启动的时候如果快照间隔内写入量大，仍然会有大量的io影响启动速度。
> 
> 这个场景可以具体描述下吗？

虽然现在业务上自己保存了 applied_index，但是服务启动的时候， raft在加载snapshot的时候会读取上一次的last apply id。然后状态机会从该id进行重放。假设快照间隔为半小时，业务上保存的最新applied_index 可能是 10w，但是raft snapshot包含的上一次 applied index可能只有1w. 这时候重启的话 fsm会去 读取 1w-10w这些raft log 重放，虽然on apply的时候会直接忽略。当业务吞吐比较高的时候，业务保存的 applied index和snapshot的index之间的gap可能很大，这些gap的日志都会在启动的时候加载进内存进行重放影响启动速度

**Comment by PFZheng** [comment]
> > > 目前存在的问题是启动的时候如果快照间隔内写入量大，仍然会有大量的io影响启动速度。
> > 
> > 
> > 这个场景可以具体描述下吗？
> 
> 虽然现在业务上自己保存了 applied_index，但是服务启动的时候， raft在加载snapshot的时候会读取上一次的last apply id。然后状态机会从该id进行重放。假设快照间隔为半小时，业务上保存的最新applied_index 可能是 10w，但是raft snapshot包含的上一次 applied index可能只有1w. 这时候重启的话 fsm会去 读取 1w-10w这些raft log 重放，虽然on apply的时候会直接忽略。当业务吞吐比较高的时候，业务保存的 applied index和snapshot的index之间的gap可能很大，这些gap的日志都会在启动的时候加载进内存进行重放影响启动速度

可以缩小 snapshot 周期。基于 rocksdb 的 snapshot 可以做到开销非常小，只需要 hook install snapshot 的过程。利用代码里提供的 BufferedSequentialReadFileAdaptor 和 BufferedSequentialWriteFileAdaptor 可以把 rocksdb 中的数据当作字节流一样处理。 @Edward-xk 有空更新一个 example 或者文档过来吧。

**Comment by lintanghui** [comment]
> > > > 目前存在的问题是启动的时候如果快照间隔内写入量大，仍然会有大量的io影响启动速度。
> > > 
> > > 
> > > 这个场景可以具体描述下吗？
> > 
> > 
> > 虽然现在业务上自己保存了 applied_index，但是服务启动的时候， raft在加载snapshot的时候会读取上一次的last apply id。然后状态机会从该id进行重放。假设快照间隔为半小时，业务上保存的最新applied_index 可能是 10w，但是raft snapshot包含的上一次 applied index可能只有1w. 这时候重启的话 fsm会去 读取 1w-10w这些raft log 重放，虽然on apply的时候会直接忽略。当业务吞吐比较高的时候，业务保存的 applied index和snapshot的index之间的gap可能很大，这些gap的日志都会在启动的时候加载进内存进行重放影响启动速度
> 
> 可以缩小 snapshot 周期。基于 rocksdb 的 snapshot 可以做到开销非常小，只需要 hook install snapshot 的过程。利用代码里提供的 BufferedSequentialReadFileAdaptor 和 BufferedSequentialWriteFileAdaptor 可以把 rocksdb 中的数据当作字节流一样处理。 @Edward-xk 有空更新一个 example 或者文档过来吧。

目前是使用rocksdb的checkpoint执行快照，install的过程也是直接将rocksdb的sst作为文件直接拷贝。
减少snapshot周期可能存在一个风险。B 从A 拷贝snapshot,  拷贝完成前，A 又执行了snapshot，这时候A 会truncate prefix log。truncate log可能导致当B 完成install的时候，拿到snapshot的last index 而此时A 上面index对应的日志已经又被truncate。导致又再次触发 B 进行install。如果snapshot比较大的话，而周期又比较小的话，可能会导致每次B install完成后index 已经被删除从而再次触发install

**Comment by PFZheng** [comment]
> > > > > 目前存在的问题是启动的时候如果快照间隔内写入量大，仍然会有大量的io影响启动速度。
> > > > 
> > > > 
> > > > 这个场景可以具体描述下吗？
> > > 
> > > 
> > > 虽然现在业务上自己保存了 applied_index，但是服务启动的时候， raft在加载snapshot的时候会读取上一次的last apply id。然后状态机会从该id进行重放。假设快照间隔为半小时，业务上保存的最新applied_index 可能是 10w，但是raft snapshot包含的上一次 applied index可能只有1w. 这时候重启的话 fsm会去 读取 1w-10w这些raft log 重放，虽然on apply的时候会直接忽略。当业务吞吐比较高的时候，业务保存的 applied index和snapshot的index之间的gap可能很大，这些gap的日志都会在启动的时候加载进内存进行重放影响启动速度
> > 
> > 
> > 可以缩小 snapshot 周期。基于 rocksdb 的 snapshot 可以做到开销非常小，只需要 hook install snapshot 的过程。利用代码里提供的 BufferedSequentialReadFileAdaptor 和 BufferedSequentialWriteFileAdaptor 可以把 rocksdb 中的数据当作字节流一样处理。 @Edward-xk 有空更新一个 example 或者文档过来吧。
> 
> 目前是使用rocksdb的checkpoint执行快照，install的过程也是直接将rocksdb的sst作为文件直接拷贝。
> 减少snapshot周期可能存在一个风险。B 从A 拷贝snapshot, 拷贝完成前，A 又执行了snapshot，这时候A 会truncate prefix log。truncate log可能导致当B 完成install的时候，拿到snapshot的last index 而此时A 上面index对应的日志已经又被truncate。导致又再次触发 B 进行install。如果snapshot比较大的话，而周期又比较小的话，可能会导致每次B install完成后index 已经被删除从而再次触发install

install snapshot 过程中 truncate prefix 的 case 应该概率很小，snapshot 被引用的时候是不会删除的，truncate prefix 的时候也会额外保留一个周期的日志

**Comment by PFZheng** [comment]
![image](https://user-images.githubusercontent.com/3984083/106717442-b4a85880-663a-11eb-8e7f-e2427039f328.png)
参考这里（log_manager.cpp），这里保证了 log 会多保留一个周期

**Comment by lintanghui** [comment]
> ![image](https://user-images.githubusercontent.com/3984083/106717442-b4a85880-663a-11eb-8e7f-e2427039f328.png)
> 参考这里（log_manager.cpp），这里保证了 log 会多保留一个周期

对的 snapshot本身有引用没有问题，就是当snapshot本身比较大的时候，可能整个install时间超过两个周期，那么就可能会出现truncate的情况了。 truncate 的时候是否可以考虑判断下当前被引用的snapshot的最小last index。 如果当前被引用的snapshot的last index < truncate index, 则保留 [last_index,truncate index] 这一段日志

**Comment by PFZheng** [comment]
> > ![image](https://user-images.githubusercontent.com/3984083/106717442-b4a85880-663a-11eb-8e7f-e2427039f328.png)
> > 参考这里（log_manager.cpp），这里保证了 log 会多保留一个周期
> 
> 对的 snapshot本身有引用没有问题，就是当snapshot本身比较大的时候，可能整个install时间超过两个周期，那么就可能会出现truncate的情况了。 truncate 的时候是否可以考虑判断下当前被引用的snapshot的最小last index。 如果当前被引用的snapshot的last index < truncate index, 则保留 [last_index,truncate index] 这一段日志

嗯，这个是可以的

**Comment by lyng-x** [comment]
> > > > 目前存在的问题是启动的时候如果快照间隔内写入量大，仍然会有大量的io影响启动速度。
> > > 
> > > 
> > > 这个场景可以具体描述下吗？
> > 
> > 
> > 虽然现在业务上自己保存了 applied_index，但是服务启动的时候， raft在加载snapshot的时候会读取上一次的last apply id。然后状态机会从该id进行重放。假设快照间隔为半小时，业务上保存的最新applied_index 可能是 10w，但是raft snapshot包含的上一次 applied index可能只有1w. 这时候重启的话 fsm会去 读取 1w-10w这些raft log 重放，虽然on apply的时候会直接忽略。当业务吞吐比较高的时候，业务保存的 applied index和snapshot的index之间的gap可能很大，这些gap的日志都会在启动的时候加载进内存进行重放影响启动速度
> 
> 可以缩小 snapshot 周期。基于 rocksdb 的 snapshot 可以做到开销非常小，只需要 hook install snapshot 的过程。利用代码里提供的 BufferedSequentialReadFileAdaptor 和 BufferedSequentialWriteFileAdaptor 可以把 rocksdb 中的数据当作字节流一样处理。 @Edward-xk 有空更新一个 example 或者文档过来吧。

缩短snapshot的周期听起来可以解决gap的问题，BufferedSequentialReadFileAdaptor 和BufferedSequentialWriteFileAdaptor 处理rocksdb的数据的作用是什么？另外example和文档有出处了吗？

**Comment by luobuda** [comment]
可以增加一些策略来主动snapshot，https://github.com/baidu/BaikalDB/blob/43998f9631e36936bdebff7bc59000e6af6a7abc/src/store/region.cpp#L3210
