### ISSUE TITLE
如果业务主动让leader transfer_leader到一个已经宕机的peer的时候（业务不知道peer dead），这时候在一个election_timeout的时间内会无主

### ISSUE THREAD

**Issue by myccccccc** [baidu/braft#264]
能不能通过replicator的_consecutive_error_times来判断如果peer dead，transfer_leader的时候就不要变成STATE_TRANSFERRING了，而是直接返回transfer_leader失败，这样就不会有一个election_timeout的时间内无主

**Comment by myccccccc** [comment]
@PFZheng PTAL

**Comment by PFZheng** [comment]
可以
