### ISSUE TITLE
关于braft何时发起noop提交之前log的问题

### ISSUE THREAD

**Issue by daipeixian** [baidu/braft#265]
你好 非常感谢你们提供的这个braft库，读完代码之后受益匪浅，近日突然遇到一个问题想请教下你们
![image](https://user-images.githubusercontent.com/19338923/110884295-dd013200-831f-11eb-81f5-989f096db8fe.png)
新的leader当选后会发送一条noop log来触发之前的任期的log隐式提交， 但是我找了很久的代码也没有找到对ENTRY_TYPE_NO_OP这个操作发起的代码， 所以这里请教下 这个noop log是在什么代码的哪一部分发起的呢 谢谢

**Comment by killme2008** [comment]
`ENTRY_TYPE_CONFIGURATION`替代了这个角色，在 become leader 后会将当前 conf 作为日志提交

https://github.com/baidu/braft/blob/master/src/braft/node.cpp#L1888

我猜测本来是设计了 NO_OP，后来发现是没有必要，但是继续保留了，还需要 braft 的作者来解释

**Comment by lichuang** [comment]
在大论文《consensus: bridging theory and practice》的3.6.2小节，讲过每个新的leader在选举成功之后，不能马上就提交上一任leader提交的日志，取而代之的，是成为leader之后提交一个空的日志（即这里的NOP），或者就是前面同学提到的提交一次conf，如果成为新leader之后的这一次提交都能成功，那么就可以保证在此之前的日志也都成功提交了。

因此，不论是NOP，还是提交conf，本质都是为了保证这一点。

**Comment by daipeixian** [comment]
明白了 感谢各位大佬的回答

**Comment by daipeixian** [comment]
> `ENTRY_TYPE_CONFIGURATION`替代了这个角色，在 become leader 后会将当前 conf 作为日志提交
> 
> https://github.com/baidu/braft/blob/master/src/braft/node.cpp#L1888
> 
> 我猜测本来是设计了 NO_OP，后来发现是没有必要，但是继续保留了，还需要 braft 的作者来解释

大佬们有跑通过jepsen测试吗 我这边跑的过程中遇到不少问题，没啥文档可以查
比如
![image](https://user-images.githubusercontent.com/19338923/114967952-f7db3f00-9ea7-11eb-8175-acf9c462a8b2.png)
atomic_test -op=cas的时候  由于
![image](https://user-images.githubusercontent.com/19338923/114968009-104b5980-9ea8-11eb-9550-288e066bc74b.png)
return EIO的原因导致test的时候抛出了no_zero的异常 这种情况是正常的吗
