### ISSUE TITLE
删除快照前的日志时，如果此时数据并未在底层落盘，是否会造成数据丢失？

### ISSUE THREAD

**Issue by AppleTp** [baidu/braft#281]
braft会在快照生成后删除上一个快照点之前的日志，而生成的快照点是根据applied_index而来的，但是如果底层不是实时落盘，则applied_index以及之前的一段日志对应数据可能还未落盘，如果此时将之前日志删除（虽然删除的是前一个快照点前的日志，但仍有可能未落盘），如果出现重启，则在回放日志时，因为底层数据未落盘丢失，而该部分只在快照中存在，重放日志时并不会向底层重写该数据，底层是否会出现数据丢失？

**Comment by PFZheng** [comment]
快照 + 快照之后的 log 数据回放可以得到完整的数据，快照之前的 log 可有可无。快照本身在生成的时候需要保证快照点的数据落盘。

**Comment by AppleTp** [comment]
> 快照 + 快照之后的 log 数据回放可以得到完整的数据，快照之前的 log 可有可无。快照本身在生成的时候需要保证快照点的数据落盘。

谢谢回复，目前快照点是基于applied_index生成的，但是applied_index对应的日志此时可能并未落盘，所以需要用户来修改快照点生成的逻辑，是吗？

**Comment by PFZheng** [comment]
> > 快照 + 快照之后的 log 数据回放可以得到完整的数据，快照之前的 log 可有可无。快照本身在生成的时候需要保证快照点的数据落盘。
> 
> 谢谢回复，目前快照点是基于applied_index生成的，但是applied_index对应的日志此时可能并未落盘，所以需要用户来修改快照点生成的逻辑，是吗？

快照的目的是压缩之前的 log 数据，理论上应该是一份完整、独立的数据，不依赖于 log 的存在与否。
举个例子，如果是一个全内存的状态机，最简单的一种实现方式就是把当时内存状态 dump 一份，这个 dump 出来的内存状态是包含 applied index 数据的，只和 log 是否被多数节点落盘有关系，和本节点是否落盘没有必然联系。

**Comment by AppleTp** [comment]
> > > 快照 + 快照之后的 log 数据回放可以得到完整的数据，快照之前的 log 可有可无。快照本身在生成的时候需要保证快照点的数据落盘。
> > 
> > 
> > 谢谢回复，目前快照点是基于applied_index生成的，但是applied_index对应的日志此时可能并未落盘，所以需要用户来修改快照点生成的逻辑，是吗？
> 
> 快照的目的是压缩之前的 log 数据，理论上应该是一份完整、独立的数据，不依赖于 log 的存在与否。
> 举个例子，如果是一个全内存的状态机，最简单的一种实现方式就是把当时内存状态 dump 一份，这个 dump 出来的内存状态是包含 applied index 数据的，只和 log 是否被多数节点落盘有关系，和本节点是否落盘没有必然联系。

非常感谢，抱歉我没交代清楚背景。我刚提到的落盘其实不是日志的落盘，而是在on_apply接口中进行数据写入，真实数据的落盘。所以我提到的可能出现数据丢失并不是日志丢失，而是日志对应的数据在底层存储上的丢失，这种情况，是不是需要用户修改快照点的生成，保证快照生成时，快照点之前的数据已经在底层落盘？

**Comment by PFZheng** [comment]
> > > > 快照 + 快照之后的 log 数据回放可以得到完整的数据，快照之前的 log 可有可无。快照本身在生成的时候需要保证快照点的数据落盘。
> > > 
> > > 
> > > 谢谢回复，目前快照点是基于applied_index生成的，但是applied_index对应的日志此时可能并未落盘，所以需要用户来修改快照点生成的逻辑，是吗？
> > 
> > 
> > 快照的目的是压缩之前的 log 数据，理论上应该是一份完整、独立的数据，不依赖于 log 的存在与否。
> > 举个例子，如果是一个全内存的状态机，最简单的一种实现方式就是把当时内存状态 dump 一份，这个 dump 出来的内存状态是包含 applied index 数据的，只和 log 是否被多数节点落盘有关系，和本节点是否落盘没有必然联系。
> 
> 非常感谢，抱歉我没交代清楚背景。我刚提到的落盘其实不是日志的落盘，而是在on_apply接口中进行数据写入，真实数据的落盘。所以我提到的可能出现数据丢失并不是日志丢失，而是日志对应的数据在底层存储上的丢失，这种情况，是不是需要用户修改快照点的生成，保证快照生成时，快照点之前的数据已经在底层落盘？

snapshot_save done->Run() 返回之前确保落盘完成
