### ISSUE TITLE
不讲bug只讲生态

### ISSUE THREAD

**Issue by tbago** [baidu/braft#296]
首先非常感谢baidu能开源这么优秀的功能完备的raft框架。
然后我有几点关于braft中的建议：
1、没有官方参考资料，参照braft的后继者阿里的[SofaJRaft](https://www.sofastack.tech/projects/sofa-jraft/overview/)；
2、braft的文档写的太简陋了，内容明显是没有经过整理的零星资料，而且内容不全，只能靠阅读源码；
3、没有官方交流群，提的Issue貌似也很少有回应；

个人愚见，做开源不是将一套源码开放出来就可以了，这样是很难吸引开发者来贡献完善代码的哦。

**Comment by PFZheng** [comment]
感谢关注 braft，你说的这些问题确实是存在的。目前 braft 的现状是没有全职的开发团队，几位维护的同学平时都有各自的研发工作，回复 issue 的及时程度就不太能得到保证。
文档方面，可能对于使用者来说，如何正确的实现 snapshot 是最难的问题，以及如何和一些常见的系统整合（RocksDB 是最典型的）。这部分的文档。
微信有一个小群，可以加 zhengpf__87 或 flyprettyboy，备注 braft 加到群里。
