### ISSUE TITLE
NodeImpl::init方法中，init_meta_storage为什么要调用2次？

### ISSUE THREAD

**Issue by fsindustry** [baidu/braft#310]
node.cpp文件
NodeImpl::init方法，第511行 和 第560行调用了2次init_meta_storage方法，请问有什么作用吗？

![image](https://user-images.githubusercontent.com/12935987/128485758-41089767-a012-4b88-88ec-4512523fded6.png)
![image](https://user-images.githubusercontent.com/12935987/128485799-57147f8a-408c-4bec-aeb7-50a526941378.png)

**Comment by Edward-xk** [comment]
> node.cpp文件
> NodeImpl::init方法，第511行 和 第560行调用了2次init_meta_storage方法，请问有什么作用吗？
> 
> ![image](https://user-images.githubusercontent.com/12935987/128485758-41089767-a012-4b88-88ec-4512523fded6.png)
> ![image](https://user-images.githubusercontent.com/12935987/128485799-57147f8a-408c-4bec-aeb7-50a526941378.png)

这个是之前一次pick代码自动merge失效引入的问题，多谢指出！
已经提 fix patch了。
