### ISSUE TITLE
bootstrap启动数据一致性问题

### ISSUE THREAD

**Issue by Tachone** [baidu/braft#313]
version: braft v1.1.2  
cpu_arch: x86_64

ABC三个节点，每个节点都有一个snapshot(从其他raft集群拷贝过来的)存放kv数据， snapshot中最新的index分别为indexA， indexB， indexC；节点使用braft::bootstrap(const braft::BootstrapOptions &opt)启动，以节点A为例:
`
opt.group_conf=ABC
opt.last_log_index=indexA
opt...
braft::bootstrap(opt)
braft::init(node_opt)
`
期望每个节点带数据bootstrap启动， 之后选举出leader组成集群对外服务。

但在实际场景中发现以下不符合数据一致性的case：
假设indexA=3, indexB=3, indexC=4，均为data entry， C先启动，之后AB启动

1. C启动， bootstrap写入一条uncommitted log(term=1, index=5)，init node，重复发起pre_vote
2. A启动， boostrap写入一条uncommitted log(term=1, index=4),  init node，收到C发起选举日志，因为log indexC(4) > indexA(3)， 投票给C， C成为leader
3. C写入一条no-op log(实现上是configuration log)(term=2, index=6)，确定comitted_index=6
4. 当前A的log index为 [4, 4]， C的 log index为 [5, 6] ，理论上因为C没有和A match的log(index=4, term=1)， C应该传输snapshot给A，但是实际上A接收到来自C的append entries，follower set_last_comitted_index=6，将 A[4,6] 的log都做了committed并apply， 问题出现了 A index=4的log是自己bootstrap写入的那一条conf log， 并不是C snapshot中的那一条data log，由此A缺少了index=4的data log

麻烦braft的同学看下在这个场景下的处理是不是有一致性的问题

**Comment by PFZheng** [comment]
> 当前A的log index为 [4, 4]， C的 log index为 [5, 6] ，理论上因为C没有和A match的log(index=4, term=1)， C应该传输snapshot给A，但是实际上A接收到来自C的append entries

这儿日志能连续上（C 的 snapshot 里隐含了用作判断的 prev_term, prev_log_index），所以收到append entries是合理的。
bootstrap 接口由于是外部强行塞入数据给 braft，需要在流程上保证原有数据是等价的。

**Comment by Tachone** [comment]
@PFZheng  bootstrap do_snapshot后写入一条conf log的目的只是为了更新当前节点组的configuration吗？
对于上面的case我想到一种解决方式，参考bootstrap新加一个func，do_snapshot之后不再写入conf log， 而是直接更新snapshot meta中的peers为传入的opt.group_conf， 这样对于ABC这个节点组来说，snapshot可以保证数据连续等价，configuration也是一致的，可以带数据组成raft集群对外服务，有什么建议吗？

**Comment by PFZheng** [comment]
> @PFZheng bootstrap do_snapshot后写入一条conf log的目的只是为了更新当前节点组的configuration吗？
> 对于上面的case我想到一种解决方式，参考bootstrap新加一个func，do_snapshot之后不再写入conf log， 而是直接更新snapshot meta中的peers为传入的opt.group_conf， 这样对于ABC这个节点组来说，snapshot可以保证数据连续等价，configuration也是一致的，可以带数据组成raft集群对外服务，有什么建议吗？

你说的这个改动并没有本质区别吧。这几个snapshot的term+index需要保证对齐，你描述的这个case仍然是有问题的，日志连不上会触发 install snapshot，这和单副本启动再add peer一样了

**Comment by Tachone** [comment]
还是有区别的，对于用户来说可以不用保证多个节点snapshot index的对齐(term=1)，日志连不上的节点都可以通过install snapshot的方式对齐数据， 起码能保证线性一致性，而不是像上述case中C成为leader的情况下， A缺少index=4的data log

**Comment by PFZheng** [comment]
通过 install snapshot 补齐，起一个副本 add peer 就行。bootstrap 3 个副本的意义就在于不希望拖取数据。至于 index 的问题，因为这个是业务层决定的，去保证一致也不是特别困难的事情（例如直接使用老复制组的某个特定 log index）。

**Comment by Tachone** [comment]
多谢回复， pr我关掉了
