### ISSUE TITLE
使用grpc client连接leader node出错

### ISSUE THREAD

**Issue by OblivionStaff** [baidu/braft#325]
为了在另外的project中连接基于braft开发的数据库，尝试用grpc client访问各个节点，查询到主节点后读写。grpc client可以正常请求follower节点，但与leader node的通信出错。其中server 端打出 Unknown setting, id=65027 value=1 这种错误信息，而client端打出 Fail to parse http body as rpc.UpdateRequest这种错误。

目前为了回避该问题，添加了一个新的brpc::Server，用一个新的端口和grpc通信。
请问如果无法在client端安装braft，是否有更好的方案？

**Comment by PFZheng** [comment]
没明白你问的这个问题，leader 和 follower 上 service 部分应该是一致的

**Comment by OblivionStaff** [comment]
grpc client可以和follower上的service通信，但与leader上的service通信出错，除非换一个braft没有使用的端口

**Comment by PFZheng** [comment]
> grpc client可以和follower上的service通信，但与leader上的service通信出错，除非换一个braft没有使用的端口

follower上也有一样的service，不会去做区分的，你可以切主下看看（stop 掉旧的 leader）

**Comment by OblivionStaff** [comment]
1. 只有我用的某个proto会出现这种现象，换个service是正常的
2. 用了kreya测试该proto，也是正常的
我可能需要再定位一下问题

**Comment by OblivionStaff** [comment]
[feature_lib.proto.txt](https://github.com/baidu/braft/files/7263171/feature_lib.proto.txt)
将context.set_compression_algorithm(GRPC_COMPRESS_DEFLATE)注释掉后，现象消失了
``` cpp
        ClientContext context;
        //context.set_compression_algorithm(GRPC_COMPRESS_DEFLATE);
        auto deadline = std::chrono::system_clock::now() +
                std::chrono::milliseconds(timeout_ms_);
        context.set_deadline(deadline);
        auto status = stubs_.at(leader_endpoint)->Query(&context, request, &response);
```

**Comment by chenzhangyi** [comment]
brpc不支持deflate， 有需要可以去brpc项目中提一个issue
