### ISSUE TITLE
save snapshot 成功后，follower 节点的 raft log 不自动清理。

### ISSUE THREAD

**Issue by ZTJiu** [baidu/braft#337]
我的服务比较特殊，save snapshot 的时候会启动一组线程把数据写到 HDFS 。所以 on_snapshot_save 里面啥也没做。

void on_snapshot_save(braft::SnapshotWriter* writer, braft::Closure* done) {
  LOG(INFO) << "save snapshot done";
  if (done) done->Run();
}

测试过程中发现，leader 节点在 save snapshot 后会自动清理 raft log，而两个 follower 节点一直都没有清理 raft log，导致占用了很多的磁盘资源。麻烦问下可能是什么原因导致的？

**Comment by ZTJiu** [comment]
这是 leader 节点保存 snapshot 的相关日志：

I1119 12:00:00.412374 36927 node.cpp:917, do_snapshot] node grpc_colossusSimTest3:s1:192.168.10.15:55666:0 starts to do snapshot
I1119 12:00:00.412477 36927 checkpoint.cc:247, SaveCheckpoint] begin save checkpoint: /home/user/xxxx
I1119 12:00:00.412503 36751 simple_raft.cc:153, on_snapshot_save] save snapshot done
I1119 12:00:00.457088 36751 snapshot.cpp:638, close] Deleting /data/web_server/colossus_raft/snapshot/snapshot_00000000000033751898
I1119 12:00:00.457110 36751 snapshot.cpp:644, close] Renaming /data/web_server/colossus_raft/snapshot/temp to /data/web_server/colossus_raft/snapshot/snapshot_00000000000033751898
I1119 12:00:00.457124 36751 snapshot.cpp:516, destroy_snapshot] Deleting /data/web_server/colossus_raft/snapshot/snapshot_00000000000032694676
I1119 12:00:00.457233 36751 snapshot_executor.cpp:234, on_snapshot_save_done] node grpc_colossusSimTest3:s1:192.168.10.15:55666:0 snapshot_save_done, last_included_index=33751898 last_included_term=6
I1119 12:00:00.590548 36775 log.cpp:1136, save_meta] log save_meta /data/web_server/colossus_raft/log/log_meta first_log_index: 32694677 time: 25079
I1119 12:00:00.590641 36775 log.cpp:595, unlink] Unlinked segment `/data/web_server/colossus_raft/log/log_00000000000031618631_00000000000031637330'

**Comment by Edward-xk** [comment]
1.查看下 follower 上 snapshot 是否成功了
2.如果是成功的，在 follower 上找个最早的（预期被删除但）没被删除的日志文件，看下是否还在被进程使用中

**Comment by ZTJiu** [comment]
> 1.查看下 follower 上 snapshot 是否成功了 2.如果是成功的，在 follower 上找个最早的（预期被删除但）没被删除的日志文件，看下是否还在被进程使用中

两个 follower 上面没有任何 snapshot 相关的日志。

**Comment by Edward-xk** [comment]
在follower上看下 http://${ip}:${port}/raft_stat 页面，snapshot_timer 是 stopped 状态？

**Comment by ZTJiu** [comment]
> 在follower上看下 http://${ip}:${port}/raft_stat 页面，snapshot_timer 是 stopped 状态？

是的

ast_msg_to_now: 10
election_timer: timeout(5000ms) SCHEDULING(in 4918ms)
vote_timer: timeout(6000ms) STOPPED
stepdown_timer: timeout(5000ms) STOPPED
snapshot_timer: timeout(-1000ms) STOPPED
storage: [1, 34760477]
disk_index: 34760476
known_applied_index: 34760473
last_log_id: (index=34760477,term=6)
state_machine: Idle
last_committed_index: 34760473
last_snapshot_index: 0
last_snapshot_term: 0
snapshot_status: IDLE

**Comment by ZTJiu** [comment]
为了自己控制 snapshot 的时间点，snapshot_interval_s 设置的是 -1，所以 snapshot_timer 没有启动。

**Comment by luobuda** [comment]
> 为了自己控制 snapshot 的时间点，snapshot_interval_s 设置的是 -1，所以 snapshot_timer 没有启动。

snapshot_interval_s 设置为 -1每个peer起一个bthread定期check控制自己snapshot

**Comment by ZTJiu** [comment]
感谢解答~~

**Comment by egolearner** [comment]
> > 为了自己控制 snapshot 的时间点，snapshot_interval_s 设置的是 -1，所以 snapshot_timer 没有启动。
> 
> snapshot_interval_s 设置为 -1每个peer起一个bthread定期check控制自己snapshot

@luobuda @ZTJiu 请教下如何自己控制snapshot的时间点？
设置snapshot_interval_s为-1。
然后在检测到可以做snapshot的时候，是主动调用fsm的on_snapshot_save吗？
