### ISSUE TITLE
结束节点后，进程依然打开log/log_xxx_xxx和log/log_inprogress_xxx文件，未关闭

### ISSUE THREAD

**Issue by hyj0** [baidu/braft#363]
具体是想要踢掉这个节点，调用Node::shutdown然后调用Node::join()，lsof查看进程依然打开log文件。请问下是这样正常的吗？

**Comment by PFZheng** [comment]
join结束了没？

**Comment by hyj0** [comment]
> join结束了没？
我们用rpc请求关闭node的, 调用如下
    _node->shutdown(nullptr);
    _node->join();
, join返回了
这样有不对的地方吗?

**Comment by hyj0** [comment]
> 调用没不对，哪儿感觉引用计数没到0

_node析构时调用Release, 最终Segment析构才会释放 
我们代码的问题, 没有delete _node导致fd没有释放
