### ISSUE TITLE
response.rejected_by_lease() if else两个分支的逻辑相同. rejected_by_lease()为true时不起作用？

### ISSUE THREAD

**Issue by Jackie0423** [baidu/braft#411]
https://github.com/baidu/braft/blob/e32b78a1f4973534aaa047dc2ead9167ec091b56/src/braft/node.cpp#L1527
rejected_by_lease： true
   _pre_vote_ctx.reserve(peer_id); // reserve将该peer_id保存至set
   _pre_vote_ctx.pop_grantable_peers(&peers); // 将内部peers全部取出, 内部置空
rejected_by_lease： false
    _pre_vote_ctx.pop_grantable_peers(&peers);  // 将内部peers全部取出, 内部置空
    peers.insert(peer_id); // 插入当前peer_id

前后2个逻辑相同？

**Comment by ehds** [comment]
`pop_grantable_peers` 里面有判断如果 `_disrupted_leader.term` != 1 (说明 leader 已经被打断了)，才会返回之前在由于是因为在 lease 内才没投票的节点。

所以如果当`_disrupted_leader.term` 还未被设置时，两个分支的作用是不同的。
- 为 true(response.rejected_by_lease) 时，仅会 reserve 当前 peer_id。
- 为 false 时，peerid不会被 reserve。

**Comment by Jackie0423** [comment]
谢谢解释
