### ISSUE TITLE
定制 snapshotReader 问题。

### ISSUE THREAD

**Issue by dingxiaoshuai123** [baidu/braft#441]
请问如果要继承SnapshotReader 定制自己的 Reader ，是要把 SnapshotStorage 、SnapshotWriter 等等都重新实现吗？

**Comment by dingxiaoshuai123** [comment]
应该要实现 SnapshotStorage 的派生类，然后返回自己的 Reader 和 Writer 。

**Comment by PFZheng** [comment]
如果是snapshot是一些文件，那raft本身就能处理，如果需要从rocksdb之类的存储里转一道，可以提供一个定制的file sytem adaptor实现，在open接口里返回定制的file adaptor进行处理，BufferedSequentialReadFileAdaptor和BufferedSequentialWriteFileAdaptor可以简化一些工作

**Comment by dingxiaoshuai123** [comment]
> 如果是snapshot是一些文件，那raft本身就能处理，如果需要从rocksdb之类的存储里转一道，可以提供一个定制的file sytem adaptor实现，在open接口里返回定制的file adaptor进行处理，BufferedSequentialReadFileAdaptor和BufferedSequentialWriteFileAdaptor可以简化一些工作

感谢回复，我的 snapshot 是一些 RocksDB 的文件。我想要控制 snapshot 的产生时机和读取方式。请问是需要继承 LocalSnapshotStorage 实现一个自定义 SnapshotStorage ，只重写必要的虚函数即可，还是说需要继承 SnapshotStorage，将所有的虚函数全部重写一遍（其中大部分函数都可以复用 LocalSnapshotStorage ，不需要进行改变）。
