### ISSUE TITLE
braft 节点如何高性能判断是否是 leader 且在 lease 内？

### ISSUE THREAD

**Issue by ergesun** [baidu/braft#442]
我发现 is_leader_lease_valid api 应该是一个正确可用的方式做这件事，但性能上其内部会加互斥锁，对于高 OPS 场景这么做不太好，有什么其他的推荐的好办法？

**Comment by ehds** [comment]
is_leader_lease_valid 有 fast path 用于快速判断 lease 是否有效。

**Comment by ergesun** [comment]
@ehds 所以目前 braft 提供的 API 层面来看 is_leader_lease_valid 就是最优的了是吧？不过我看  fast path 
<img width="627" alt="image" src="https://github.com/user-attachments/assets/f11bc653-2447-4ff0-b399-a505b3bd3c26"> 里面也是加了锁的
